### ISSUE TITLE
propose a plan for how to move the rest of node api to plumbing/porcelain

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#1858]
dont do the work yet, just make the proposal here or in the doc. should not include protocol api calls which zen is going to prototype and tackle. 

note it is worth looking through this epic to see what is already in progress eg #1802

**Comment by rosalinekarr** [comment]
@phritz yep, those issues are all part of the porcelain/plumbing plan going forward.

I did mark a few as good-first-issue, but those are all incredibly simple ones. #1866 for example is just a deletion and a single line change. The code itself has already been moved to plumbing. We just need to delete some stuff in node.

I have most of the refactor planned out at this point, but I'm still trying to figure out the best solution the core of the node api itself, i.e. `init`, `mining` and some stuff dealing with protocols. I talked to @ZenGround0 about it last week, and we had a few interesting ideas that I wanted to explore further together, but since @ZenGround0 is on vacation, I'd be happy to talk it over in a video chat with you at some point.

**Comment by phritz** [comment]
hi @rosalinekarr the protocol stuff is specifically out of scope perhttps://github.com/filecoin-project/go-filecoin/issues/1858#issue-408389705, and we have #2030 to cover those. this issue is about the easy cases, lets get those covered first. 

i'm happy to look at a doc, or talk in person i have a few slots today if you want.

**Comment by rosalinekarr** [comment]
completely forgot to link the doc here: https://docs.google.com/document/d/1L5hbcDGhfH3AlMti4RQ3Zke6nc4-eGOmk9lD0nNoiEs
