### ISSUE TITLE
[bug] I shouldnt have to set an environment variable to make my daemon run properly

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-filecoin#1876]
The getting started guide says I have to run: `env FIL_USE_SMALL_SECTORS=true go-filecoin daemon`. It seems like I should just run `go-filecoin daemon` and it should do the right thing.

The default that we're expecting users to actually do should be the easiest path.

**Comment by rosalinekarr** [comment]
@acruikshank @laser, what would it take to change this?

**Comment by phritz** [comment]
it does just work if you don't set use small sectors. you get large sectors which are much slower to seal and potentially wasteful of disk space, but realistic. 

if you want to connect to the nightly you must set small sectors to true, because it is designed to operate fast and less realistically to aid in debugging. if you want to connect to the user devnet you dont have to set any env var, and this is the common case. i think the instructions convey this pretty clearly:
```
Note: if you're a developer and wish to connect to the nightly devnet rather than user devnet, you must configure your node to use small sectors, and build from the devnet-nightly tag.
```
-- https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#start-running-filecoin

is there some specific thing that it should say or do differently?

**Comment by laser** [comment]
> but 👍 it should "just work" without env vars.

> It seems like I should just run `go-filecoin daemon` and it should do the right thing.

The user cluster is configured to use real sectors. The nightly cluster is configured to use small/test sectors.

If you run `go-filecoin daemon` in an environment where `FIL_USE_SMALL_SECTORS` is *not* set to `true`, your daemon will use real, non-test, normally-sized (not small) sectors.

If you run the `daemon` and set `FIL_USE_SMALL_SECTORS` to `true`, your daemon will use the small/test sectors.

The software, as currently written, requires a developer to opt *in* to using the test/small sectors. The default behavior is to use the real/not-small sectors.

@anorth and @whyrusleeping: Do you propose to change the default sector size from real/not-test to small/test?

**Comment by phritz** [comment]
@laser we should not set the default differently, it should be realistic by default, or at least that was what we decided last we talked. i think this issue is based on old wiki content, or perhaps a mis-reading of the wiki content. or maybe i'm missing something, but see above.

**Comment by whyrusleeping** [comment]
@phritz Yeah, I think this was about old wiki content. free to close if connecting to the user devnet doesnt require setting an env var

**Comment by phritz** [comment]
you got it, thanks for bringing laser in rosalinekarr
