### ISSUE TITLE
Storage market penalization of late submitters

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#1887]
### Description
This is a stub tracking work to sync with the spec on penalization of late post submitters in the storage market.  This includes setting proving period and grace period parameters.

We need appropriate values for:

1. `miner.Actor.GracePeriodBlocks`: The number of blocks after a proving period over which a miner can still submit a post at a penalty.
2. `miner.Actor.ClientProofOfStorageTimeout`: the number of blocks between LastPoSt and the current block height after which the miner is no longer considered to be storing the client's piece and they are entitled to a refund.
3. `paymentbroker.Actor.CancelDelayBlockTime`: the number of rounds given to the miner to respond after the channel is canceled before it expires.

**Comment by anorth** [comment]
@acruikshank this may be relevant for epic #2481

**Comment by acruikshank** [comment]
@ZenGround0 Does this issue refer to the slashing of storage miner by the client for failing to prove a particular deal or the the slashing by the network for failing to prove committed storage?

**Comment by acruikshank** [comment]
I'm going to answer yes, because I need this too.

When a miner fails to submit PoSts they will hit two separate deadlines. The first is a consensus fault and subjects the miner to slashing because they are claiming storage power they do not have. The second indicates the miner is no longer fulfilling their storage deals with clients. This deadline allows clients to reclaim their storage payments and slash the miner for damages. The second is considered to have more serious consequences, so the miner is given more time to resume their PoSts.
