### ISSUE TITLE
Version 0.0.2 still has previous version in package.json

### ISSUE THREAD

**Issue by imrehg** [filecoin-project/go-filecoin#1990]
Even though the tags suggest that this project is on version `0.0.2` (see [tree at that tag](https://github.com/filecoin-project/go-filecoin/tree/0.0.2)), the version in `package.json` is still 0.0.1 

https://github.com/filecoin-project/go-filecoin/blob/271a6812e23e3ccd80642d251e1c1f449459a8b7/package.json#L205

Is this an oversight, or I'm missing something about how this project is versioned?

**Comment by phritz** [comment]
also @travisperson seems like these versions are causing confusion in slack as well?

**Comment by gmasgras** [comment]
> @gmasgras is there anything intentional going on with versioning here? i think this is an unintended side effect of tagging for deployment?

The only tag that triggers a devnet deploy is `devnet-user`
Tagging something with `0.x.x` doesn't trigger a devnet deploy, it only triggers a GitHub Release™️ . The release never actually got published because the build process failed to create an OSX tarball (some tests were failing during Lauch Week).

I will re-tag the commit that `usernet` is running at with `0.0.2` (in order to publish a GH Release) once using a prebuilt binary to join the `usernet` is supported

**Comment by rosalinekarr** [comment]
@phritz @travisperson, should we update or maybe just omit the version from `package.json`?

**Comment by rosalinekarr** [comment]
Also, I'm relabelling as docs, since this isn't a breaking issue.

**Comment by anorth** [comment]
I believe this will become a non-issue when we move to go modules #2307
