### ISSUE TITLE
[bug]Error: failed to open datastore: Unable to mmap RDWR log file: exec format error.

### ISSUE THREAD

**Issue by xcshuan** [filecoin-project/go-filecoin#2002]
**Describe the bug**
WhenI use WSL(Ubuntu) to compile go-filecoin, it finished, but when I run 
$go-filecoin init
$go-filecoin daemon
it output: Error: failed to open datastore: Unable to mmap RDWR log file: exec format error.

Is WSL cannot compatible with go-filecoin??

**To Reproduce**
1. act according go-filecoin Readme
2. Run this command $go-filecoin init $go-filecoin daemon
3. See error: Error: failed to open datastore: Unable to mmap RDWR log file: exec format error.

**Expected behavior**
as README

**Screenshots**
![default](https://user-images.githubusercontent.com/24284441/52901550-02eea200-3240-11e9-9abc-9fe10793aa8d.png)

**Desktop (please complete the following information):**
 - OS:WSL(Ubuntu18.04 on Win10)

**Comment by schomatis** [comment]
This Badger error was historically associated with not-enough-memory issues (Badger is trying to `mmap` a 2 GB file), but the `exec format error` may indicate otherwise. @xcshuan, could you take a look at this WSL related issue, https://github.com/Microsoft/WSL/issues/2121, to see if it help elucidate the source of the problem a bit more please?

**Comment by xcshuan** [comment]
@schomatis Oh, Thanks, I guess it cannot fixed right now, so I have intstalled a true Ubuntu18.04 to test Filecoin.

**Comment by tycholiu** [comment]
also went into this issue. Only sub command init and daemon report "exec format error". Other sub command are OK. @schomatis did you resolve this later ?
