### ISSUE TITLE
[bug] wallet export gives different info with different encoding

### ISSUE THREAD

**Issue by imrehg** [filecoin-project/go-filecoin#2004]
**Describe the bug**

When `wallet export` is called without any encoding, it gives `Address`, `PrivateKey` (in some format), and `Curve`.
When called with `--enc=json`, it just gives `privateKey` (in a different format), and `curve`.

Feels unusual that the encoding changes what fields are available, and change the format of those fields.

**To Reproduce**

Initialize filecoin, then run:
```
export ADDR=$(go-filecoin wallet addrs ls)
go-filecoin wallet export $ADDR
go-filecoin wallet export $ADDR --enc=json
```
Compare the results.

**Expected behavior**
The two outputs having the same fields and the same values.

**Screenshots**
```
$ go-filecoin version
commit: 271a6812e23e3ccd80642d251e1c1f449459a8b7
```

**Comment by rosalinekarr** [comment]
@rkowalick, when you get back, can you look into this bug?

**Comment by mishmosh** [comment]
Removing P0 label (reserved for devnet-crashing panics, etc.).

**Comment by rkowalick** [comment]
Sorry, just seeing this now, I will work on it

**Comment by rkowalick** [comment]
Update: the `wallet export` command with `--enc=json` will still only return the private key and the curve used, since this command is designed to write files suitable for consumption by the `wallet import` command, and isn't really designed for human use.

The `wallet export` command with no encoding specified will still return address, private key, and curve, but the private key will have the same output format as the one used for `--enc=json`.
