### ISSUE TITLE
Client and miner should reject attempts to store a piece larger than sector size

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2034]
### Description
A client can attempt to propose a storage deal for a file that's larger than the miner sector size. This apparently just times out at the client.

See https://github.com/filecoin-project/go-filecoin/issues/1965#issuecomment-464187940

(There may have been other circumstances related to invalid nonces that caused the particular failure observed above)

### Acceptance criteria
- The client rejects attempts to store a too-large file without consulting the miner/network
- In case a client misbehaves, a miner immediately rejects a proposal for a too-large file

### Risks + pitfalls
None

### Where to begin
protocol/storage/client.go

**Comment by rosalinekarr** [comment]
Ideally, we should automatically split up large files, but I'm not sure how that user experience would work. @ZenGround0, any thoughts?

**Comment by phritz** [comment]
for now we should just error out if they try to do it. a nice way to do it would be to surface sector size in plumbing via a params struct, and rely on that. we could easily extract params like sector size from sector base before initializing the plumbing.

**Comment by rkowalick** [comment]
This is blocked pending design discussion. The problem lies in the following fact:

1. Accurate sector size can only be obtained from the initialized sector builder.
1. Creation of a sector builder requires a mining address.
1. A mining address can only be created with a createMiner message on chain. This requires a pledge, collateral, and gas.

**Comment by rkowalick** [comment]
Currently, the storage miner will mark a deal as "Failed" in the event the piece size is larger than the sector size. The problem is that the client has no way of knowing about this status change and assumes everything works after the initial deal response (which occurs before an attempt is made to seal the sector).

I have a PR that makes the miner fail the status of the deal in the event the piece size is greater than the sector size: https://github.com/filecoin-project/go-filecoin/pull/2439

The problem is that this is a bandaid for this specific problem, and having some mechanism for the storage miner to communicate errors to the client would not only resolve this issue, but propagate other failures to the client as well.

**Comment by rkowalick** [comment]
## Current state

Since the fix of the `propose-storage-deal` timeout, some more investigations and some talks with laser have led me to conclude that this does _sort of_ work properly, in the sense that the deal state does get updated, but after the `client propose-storage-deal` command completes.

The storage client needs to check the deal with `client query-storage-deal` and see a status of `posted` to actually confirm that the deal was correctly executed.

The current retrieval script doesn't make this check before attempting to retrieve the piece it stored, so the retrieval step can, in certain circumstances, fail to retrieve the piece. I am going to make a PR for that check and link it to this issue.

## Future?

For the future, we have a few options:
(a) Have the client daemon perform this check before sending the piece over the network. This requires some changes to how one obtains the sector size, since there are a few issues that have been enumerated in #1932. I am currently working on this issue with @laser.
(b) Have the miner daemon check the size of the incoming piece before attempting to process it. This will allow the `client propose-storage-deal` command to return failure.

**Comment by anorth** [comment]
(b) sounds good and probably necessary. Long term, I imagine the piece data
will need to be streamed so the expected size provided out of band, and
hence easy to check.

(a) would also be great if possible, but if it's a giant yak shave, we
could forgo it in return for a solid implementation of (b).
