### ISSUE TITLE
[bug] balance and miner cannot sync to local

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/go-filecoin#2166]
the balance application is successful,Then execute the command:
# go-filecoin message wait zDPWYqFCsQXfHHk1e7aSZWqkVfohHKi5gY9m2DUGzGTJYg7ZLXUZ,
will remain in the wait state,It’s been like this for a few days.Miner application is also.Just executed correctly when installing,don''t working lately.

**Comment by rkowalick** [comment]
@diwufeiwen 

Thanks for the feedback. Could you tell us which devnet you are using? We have been having some issues with the user dev net lately, so the behavior you are seeing could be a result of that.

**Comment by rkowalick** [comment]
We have seen a lot of issues around being unable to sync to the user devnet properly. The documentation has been updated here: https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#installing-from-source to include the requirement that one must use code built with the `devnet-user` git tag in order to be able to sync to the user devnet. Before installing and building, you can run
```
git fetch origin devnet-user -f
git checkout devnet-user
```
to ensure you have the correct code.

Please be aware that syncing the chain will take on the order of several hours. You can check your progress by running the command
```
$ go-filecoin show block $(go-filecoin chain head | jq .[0]['"/"'] | tr -d \")
Block Details
Miner:  fcq4npmz3uq4f4guvs00l7j6pluat3rc678vfff94
Weight: 336866.939
Height: 12810
Nonce:  0
```
and comparing the `Height` with the Block Height listed by nodes on the page
https://stats.kittyhawk.wtf/storage/mining

**Comment by diwufeiwen** [comment]
@rkowalick  go-filecoin init --devnet-user --genesisfile=http://user.kittyhawk.wtf:8020/genesis.car

**Comment by rkowalick** [comment]
@diwufeiwen That command looks correct. Is it not working?

**Comment by mishmosh** [comment]
@diwufeiwen We are closing this for now, but please reopen if you follow the instructions above and find it still doesn't work.
