### ISSUE TITLE
the TestVoucherPersistenceAndPayments test is flaky

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#2191]
### Description

The `TestVoucherPersistenceAndPayments` test has caused a few CircleCI failures:

https://circleci.com/gh/filecoin-project/go-filecoin/11838

For more background, see [this thread](https://filecoinproject.slack.com/archives/CEHHJNJS3/p1551898915174500) in Slack.

**Comment by travisperson** [comment]
Some context around the last time we saw this:

--------------------------

That may not actually be an error, it could be that the node was shut down while it was processing. Since the context is canceled during the shutdown, it looks like it was processing a block at that time. We should probably fix that by explicitly checking the returned error against `context.Canceled` and handle it differently than printing the error.

I think that would explain the flakiness, and I don't see any other reason why that context would get canceled.

Something like the following should fix this

```diff
diff --git a/node/node.go b/node/node.go
index 7ff403e0..835028c3 100644
--- a/node/node.go
+++ b/node/node.go
@@ -1117,7 +1117,7 @@ func (node *Node) handleSubscription(ctx context.Context, f pubSubProcessorFunc,
                        return
                }
 
-               if err := f(ctx, pubSubMsg); err != nil {
+               if err := f(ctx, pubSubMsg); err != nil && err != context.Canceled {
                        log.Errorf("%s(): %s", fname, err)
                }
        }
```
