### ISSUE TITLE
Don't color logs sent to a non-tty

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2195]
**Describe the bug**
Filecoin node logs, which are printed to stderr, include tags for coloring in a TTY. These make the logs hard to read in a non-TTY context.

**To Reproduce**
1. Run `./go-filecoin daemon 2>stderr.txt` for 30 seconds then kill it
2. `cat stderr.txt`, observe color because your shell is interpreting the color codes
3. `open stderr.txt` (or windows equivalent) to observe codes messing up the log in TextEdit

**Expected behavior**
Logs printed to an output that is not a TTY are not colored.

**Examples**
```
badger 2019/03/07 14:25:44 INFO: All 0 tables opened in 0s
badger 2019/03/07 14:25:44 INFO: Replaying file id: 0 at offset: 0
badger 2019/03/07 14:25:44 INFO: Replay took: 28.565µs
[0;37m14:25:44.085  INFO [0;34mchain.stor: [0mstart loading chain at tipset: { zDPWYqFCzyRooJH4TCQMFnrae4kjWLPDHRZjdYSLAYijK8s5rGsn }, height: 6005 [0;37mdefault_store.go:119[0m
[0;37m14:25:44.087  INFO [0;34mchain.stor: [0mload tipset: zDPWYqFCtGdMCWH1HCjwuHC7J7GRkaJqwzanATLTdsTyCrCAa8cp, height: 6000 [0;37mdefault_store.go:126[0m
[0;37m14:25:44.215  INFO [0;34mchain.stor: [0mload tipset: zDPWYqFCtvXuRmdLYjFwDCGzvaGLUV5rCgvtmEasXs8TqsgqViKL, height: 5400 [0;37mdefault_store.go:126[0m
[0;37m14:25:44.339  INFO [0;34mchain.stor: [0mload tipset: zDPWYqFCwyrCxW8rahkXSZrYeUTsjtkQ5n4isZPEdTEFZojYFpZs, height: 4800 [0;37mdefault_store.go:126[0m
[0;37m14:25:44.618  INFO [0;34mchain.stor: [0mload tipset: zDPWYqFCsFaNUKdTCZzmcLwsyxbWoDFCgRTdj65YYirMcUxqg9je, height: 3600 [0;37mdefault_store.go:126[0m
[0;37m14:25:44.876  INFO [0;34mchain.stor: [0mload tipset: zDPWYqFCraAgtvAfKf1v1kKUxvcfbAQ6npE6Xx4UeJwcaP6fGTkQ, height: 2400 [0;37mdefault_store.go:126[0m
[0;37m14:25:45.007  INFO [0;34mchain.stor: [0mload tipset: zDPWYqFD3azvTHxTxu8FjasuN56qYoeQrZAYG1gz6GhboHQcrP3L, height: 1800 [0;37mdefault_store.go:126[0m
[0;37m14:25:45.451  INFO [0;34mchain.stor: [0mload tipset: zDPWYqFCutuHwRZhGXzji9L4eHeoFxxNCxCruGjWje36aAvbK2XV, height: 0 [0;37mdefault_store.go:126[0m
[0;37m14:25:45.452  INFO [0;34mchain.stor: [0mfinished loading 6005 tipsets from { zDPWYqFCzyRooJH4TCQMFnrae4kjWLPDHRZjdYSLAYijK8s5rGsn } [0;37mdefault_store.go:161[0m
[0;37m14:25:54.584 [31mERROR [0;34m      node: [0mBlockSub.Next(): context canceled [0;37mnode.go:1116[0m
[0;37m14:25:54.584 [31mERROR [0;34m      node: [0mMessageSub.Next(): context canceled [0;37mnode.go:1116[0m
badger 2019/03/07 14:25:55 INFO: Storing value log head: {Fid:0 Len:0 Offset:194582422}
badger 2019/03/07 14:25:55 INFO: Force compaction on level 0 done
badger 2019/03/07 14:25:55 WARNING: While forcing compaction on level 0: Unable to fill tables
badger 2019/03/07 14:25:55 INFO: Storing value log head: {Fid:0 Len:46 Offset:12444588}
badger 2019/03/07 14:25:55 INFO: Force compaction on level 0 done
badger 2019/03/07 14:25:55 WARNING: While forcing compaction on level 0: Unable to fill tables
[0;37m14:25:55.816 [31mERROR [0;34m bootstrap: [0mgot error trying to connect to bootstrap node {ID:<peer.ID Qm*QvwuiV> Addrs:[/dns4/user.kittyhawk.wtf/tcp/9003]}: context canceled [0;37mbootstrap.go:130[0m
[0;37m14:25:55.817 [33mWARNI [0;34m   metrics: [0mHeartbeat service failed to connect for 0s: context canceled [0;37mheartbeat.go:142[0m
```
See the end of [this trace from a failing test on CI](https://files.slack.com/files-pri/TEHTVS1L6-FGP256QV8/-.txt).

**Where to start**
Start with the root `main.go`. It looks like we use some logging packages from IPFS which maybe configured by environment variable. It may be that the policy I state can't be implemented without changing that package, making this an excellent issue for an IPFS contributor.

**Comment by magik6k** [comment]
This will be easiest to fix in https://github.com/ipfs/go-log/blob/master/oldlog.go#L75, by checking `github.com/mattn/go-isatty.IsTerminal`, and if we detect a non-terminal stderr, use `colorable.NewNonColorable` to remove escape sequences.

isatty package in not gxed, and since we are switching to gomod, I'd say we should wait for that to happen first

**Comment by anorth** [comment]
Just to clarify, does `go-filecoin` need to move to gomod, or just `ipfs/go-log` in order for us to ingest a fix there?

**Comment by magik6k** [comment]
go-log is quite deep in the dependency tree, so if filecoin is about to move to godep (and other big projects already did), it doesn't really make sense to sink time into propagating gx updates, when with gomod we should be able to just update one number in this repo.

That obviously doesn't stop anyone from actually implementing the fix in go-log

**Comment by iand** [comment]
I have made a start on this, but the first step is to upgrade to go-log v2 everywhere. This is easy except for a two references to the writer package which doesn't exist any more:

 1.  `log tail` which is currently broken but could be fixed with https://github.com/ipfs/go-log/pull/87. 
 2.   Redirect logs to stdout. Could be fixed with a patch to go-log or possibly dropped as a feature since there are workarounds.

**Comment by anorth** [comment]
Thank you!

Please do the go-log upgrade in a distinct PR ahead of addressing the core of this issue.

Is the stdout redirection you refer to the `elstdout` flag? I am ok with dropping this feature. @frrist @travisperson please weigh in if you'd like to counter that.

**Comment by iand** [comment]
I have a second open PR on go-log which would allow the `elstdout` flag to be retained and would allow control over the color output. See https://github.com/ipfs/go-log/pull/88

**Comment by frrist** [comment]
The `log tail` command was added to print the event logs go-log produced to the terminal. The `elstdout` flag was added to so that go-log could said **e**vent **l**ogs to **stdout** without having to run the `log tail` command (PR here https://github.com/filecoin-project/go-filecoin/pull/860) -- this made infra slightly easier. Event logging has since been deprecated from go-log (https://github.com/ipfs/go-log/commit/eede8da5989fa4a4e2408ca2070bb12529954db0#diff-308aaa719425f4333033c97cfb3b9868L62-L68) making both of these features noops. I am okay with dropping both the `log tail` command and the `elstdout` flag as they are now obsolete.

----------------------------

Proposed solution to the op issues:
go-log has a (poorly documented) [flag](https://github.com/ipfs/go-log/blob/master/setup.go#L35) to prevent colored logging:
`env GOLOG_LOG_FMT="nocolor" ./go-filecoin daemon 2>stderr.txt`

**Comment by iand** [comment]
https://github.com/filecoin-project/go-filecoin/pull/4154 upgrades to go-log v2 to enable the `GOLOG_LOG_FMT` workaround mentioned. It also fixes log tail in the process and deprecates `elstdout`
