### ISSUE TITLE
How  to run a private chain, build a new dev-net

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/go-filecoin#2294]
I want build a dev-net for myself test, it just like 'dev-user', 'dev-test', 'dev-light'. 

I build the `go-filecoin` project, and generate the genesis.car file.

Then i run

```bash
./go-filecoin init --genesisfile=./fixtures/genesis.car
```
```bash
./go-filecoin daemon
My peer ID is QmRA7EymuNd9GBpt9SFsLy5cu5xXdtTV8jMbKy8MnkXpeH
Swarm listening on: /ip4/127.0.0.1/tcp/6000
Swarm listening on: /ip4/192.168.0.110/tcp/6000
Swarm listening on: /ip4/172.17.0.1/tcp/6000
```
But it does not create new blocks.

What should i do to make the daemon auto mining, just like `geth`.

I may not have described my problem clearly. Simply put, I want to create a new network.

**Comment by anorth** [comment]
I think this question would best be asked on https://discuss.filecoin.io/, where other users can also help and the resolution will be more discoverable in the future.

Some brief notes, though:
- Mining must be enabled on a node. See instructions at https://github.com/filecoin-project/go-filecoin/wiki/Mining-Filecoin
- For a private network, you might need to generate a different genesis. I'm not sure of mechanisms to do that right now.

@travisperson is there documentation on this anywhere? If not, let's use this issue to track it.

**Comment by travisperson** [comment]
I don't believe there is any explicit documentation yet on how to work with the genesis file. I did just merge the `localnet` utility that provides this functionality, and also can be used as source code documentation till we have something better in the wiki.

There is a bug currently do the change in address code though which I've opened PR #2317 to resolve.

Once that change has merged, users just need to build the tool, default settings are pretty close to what the devnets run. The tool defaults to small sectors, but that can be changed by passing `-small-sectors=false`. To make it a bit easier to use, there is also a `-shell` flag that can be passed which will drop the user into a shell with a go-filecoin daemon already running and ready to be used with `go-filecoin`.

_Note: Using regular sized sectors with localnet can be incredibly taxing on a system and should probably be avoided on laptops due to the number of miners running. The overall miner count can be reduced from the default `5` by passing the `-miner-count` flag._
```
go-filecoin $ cd tools/fast/bin/localnet
localnet $ go build -o localnet main.go
localnet $ ./localnet -small-sectors=false -shell
```
_I ran `./localnet -small-sectors=false -miner-count=2` on my laptop ( i7-8550U CPU @ 1.80GHz / 16GB Ram) and it took just under 40 minutes, the equivalent with small sectors took 2 minutes._

A few helpful things to note when working with localnet
1. All nodes and filecoin repositories will be cleaned up if the program exits. The program will not exit till it receives a `SIGTERM` (ctrl-c)
2. Every command that is ran will be printed to the output, along with which node ran it. The nodes repository is also printed first.
   - `08:51:48.014  INFO /tmp/local: RunCmd: /tmp/localnet417209521/0 [go-filecoin ...`
3. The stdout and stderr are written to disk under the repository directort
   - **stderr** `/tmp/localnet417209521/0/daemon.stderr`
   - **stdout** `/tmp/localnet417209521/0/daemon.stdout`
4. The localnet tool will copy the `go-filecoin` binary from `$GOPATH/src/github.com/filecoin-project/go-filecoin/` and place it in a `bin` directory under each nodes repository which is used to execute all commands. To ensure binary compatibility, it's best to execute this same binary
4. You can run commands against any of the nodes by using the `-repodir` flag with the go-filecoin binary
   - `/tmp/localnet417209521/0/bin/go-filecoin -repodir=/tmp/localnet417209521/0 id`
    

### Setting up and working with a genesis.car file

The following file describes the setup process for configuring a node to use information inside of the genesis file. Below I will talk about how to use the files inside of `fixtures` to do this process.

https://github.com/filecoin-project/go-filecoin/blob/master/tools/fast/series/setup_genesis_node.go

The genesis file contains the seed of the chain. It's basically block zero. The block contains messages that gives power to one miner and tokens to certain other address (account actors / wallets).

To use the miner in the genesis, we have to import the miner owner (account actor / wallet), configure a few values, and update the peerid associated with the miner.

_Note: The following commands assume you are running inside of the `go-filecoin` source directory._

```
$ ./go-filecoin init --genesisfile=./fixtures/genesis.car
$ ./go-filecoin daemon
```
```
$ mineraddr=$(jq -r '.Miners[0].Address' ./fixtures/gen.json)
$ peerid=$(./go-filecoin --enc=json id | jq -r '.ID')
$ ./go-filecoin config mining.minerAddress $mineraddr
$ walletaddr=$(./go-filecoin --enc=json wallet import ./fixtures/0.key | jq -r '.Addresses[0]')
$ ./go-filecoin config wallet.defaultAddress $walletaddr
$ ./go-filecoin miner update-peerid --from $walletaddr --gas-price 0 --gas-limit=300 $mineraddr $peerid
$ ./go-filecoin mining start
$ ./go-filecoin wallet balance $walletaddr
```

You should see a non-zero balance. Setting up additional miners can be achieved by following the standard method, and using this genesis node as a way to receive funds.

-----------------------------------------

Assigning this issue to myself to transfer this information to the wiki.

**Comment by yangjian102621** [comment]
@travisperson 
Thank you so much, and this problem has plagued me for a long time.

In fact, i had imported ./fixtures/0.key to my wallet. There is 1000000000000 token in the account. 

And i run the follow command to start the faucet service: 

```bash
./tools/faucet/faucet -faucet-val=1000 \
-fil-wallet=<wallet address of 0.key> \n
-limiter-expiry=24h0m0s
```
i create a new address use the command below:

```bash
./go-filecoin address new
```
Then i visited `http://localhost:9797`, and submit my new address, it return the CID.

Since I can't start mining, the new address has not receive the tokens.

Now i will try your solution, hope to solve it.

Thanks again.

**Comment by yangjian102621** [comment]
@travisperson 

I had run the master node with `./fixtures/genesis.car`, and i run the other 2 nodes with the same genesis file, then i connected to the master node use follow command:

```bash
./go-filecoin swarm connect {MASTER_NODE_ID}
```
it can sync data between them automatically. Every thing is all right.

well, now i got a problem, how to automatically connect my master node when other nodes are started?
 just like the bootstrap address of `~/.filecoin/config.json`

```javascript
"bootstrap": {
                "addresses": [
                        "/dns4/user.kittyhawk.wtf/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4",
                        "/dns4/user.kittyhawk.wtf/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4",
                        "/dns4/user.kittyhawk.wtf/tcp/9002/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY",
                        "/dns4/user.kittyhawk.wtf/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV",
                        "/dns4/user.kittyhawk.wtf/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg"
                ],
                "minPeerThreshold": 1,
                "period": "10s"
        },

```

**Comment by travisperson** [comment]
You can replace those bootstrap address with any address you want to automatically connect to when your node starts.

**Comment by yangjian102621** [comment]
@travisperson 
Hi, also some questions about the private filecoin network. i ran 3 nodes. one is the genesis, the another two are created with the same genesis file with genesis node, and i create a miner of each node. Now I have encountered some of the following questions. 

> Note: All of the following issues were encountered after upgrading to `0.2.2`

1. Every node is mining, but only the genesis node mined blocks. the another two never mine one.
2. I use node 1 post a storage deal to node 2, and it throw an error:

```bash
Error: response check failed: deal rejected: miner account (t145ezrpgjqy6wmqx42rfpnn6rxlgu7o47z3275jq) is not target of payment channel (t14s63iycmjsojuggjrq4c2hl7h6gjsldiox7ukya)
``` 
I try several times, and get the same errors.  All my operation(create miner, set price etc) is following the standard method.

**Comment by frrist** [comment]
@yangjian102621 these are really good questions to be asking!

 In the interest of spreading this knowledge to a wider audience let's continue this discussion in the [Filecoin forum](https://discuss.filecoin.io/) instead. A response there will be more visible to others in the community. Issues in this repository are reserved for development tasks and bug reports.

I am closing this issue now in favour of responding in the forum.
