### ISSUE TITLE
Mechanism for miner to drop a sector

### ISSUE THREAD

**Issue by AbelLaker** [filecoin-project/go-filecoin#2353]
### Description
Storage expires or customer cancels service, how to delete useless data

**Comment by abelchen1981** [comment]
Storage expires or customer cancels service, how to delete useless data

**Comment by rosalinekarr** [comment]
Would you mind directing this question to our [forum](https://discuss.filecoin.io) or help [slack](https://filecoinproject.slack.com) instead?

**Comment by AbelLaker** [comment]
I suggest that store  data by orders which from customers , and delete useless data files and sealed sectors by  a back-up service.

**Comment by rosalinekarr** [comment]
Oh, my mistake. I thought you were asking a question, but you were suggesting a feature.

I'm not sure where deleting old data will land in our prioritization, but this is absolutely something we're going to want to work on, so I'll update the title and add it to our workflow.

**Comment by anorth** [comment]
I have removed the word "automatically" from this issue title.

Miners will desire to keep proving stale data, even when no longer receiving client payments, in order to maintain their storage power and hence block reward. Removing sectors with no active pieces will be an explicit, opt-in action. We should of course provide that, probably via commands to list and remove such sectors.

**Comment by anorth** [comment]
In the new spec, sectors expire automatically. Reclaiming the space will be the role of the storage miner module.
