### ISSUE TITLE
Iterate over message list only once in `runMessages`

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/go-filecoin#2432]
### Description
Merge runMessages and ProcessTipSet so that we apply the first block's messages only once and pick up tipset processing on top of that state.  Affected also by #2310 

### Acceptance criteria
runMessages iterates only once through tickets

### Risks + pitfalls
certain errors are not caught, messaged and/or processed correctly

### Where to begin
see description

**Comment by anorth** [comment]
As I read the code now, I think this issue should be talking about messages rather than tickets: the tickets are not explicitly accessed here.

@ZenGround0 how do you think this should work? Does it involve merging `ProcessBlock` and `ProcessTipSet`? I infer that we still wish to maintain the requirement that a block applies cleanly to the parent state, even if in the context of the tipset under consideration it is being applied to a modified state.

**Comment by ZenGround0** [comment]
> I think this issue should be talking about messages rather than tickets

I think so too, though feel free to correct us if we're misunderstanding @shannonwells.

> I infer that we still wish to maintain the requirement that a block applies cleanly to the parent state,

Yes.  From the investigation in #3083 it is clear that (unless we change course) every block's state root needs to match up with the result of applying all of that block's messages.  This means we can't fully merge ProcessBlock and ProcessTipSet.

One optimization we haven't written yet is to merge runMessages and ProcessTipSet so that we apply the first block's messages only once and pick up tipset processing on top of that state.  Perhaps this issue could track that.

**Comment by shannonwells** [comment]
This may have been just a typo on my part. I believe this issue came from a TODO in the code. I'll correct the story.
