### ISSUE TITLE
Why do some miner Proven Storage speeds grow very fast?

### ISSUE THREAD

**Issue by sywyn219** [filecoin-project/go-filecoin#2436]
### Where to begin

Why do some miner Proven Storage speeds grow very fast, from stats.kittyhawk.wtf/storage/mining, and I am trying to store it myself, but the growth is very slow, I use the command go-filecoin client propose-storage-deal .. . Stored to my other node.
Does this require additional settings? Or is it just a different computer hardware performance？

**Comment by ElecRoastChicken** [comment]
I am seriously doubt that some miner using hyper PC running the devnet nodes in the current new devnet version~
But those particular equipments absolutely not suitable for actual minning work, at least cant be applied to large scale operation :)

**Comment by travisperson** [comment]
It's hard to say, but I'd expect it's just due to the hardware they are using. I don't know what the fastest proving times are off the top of my head (and not even sure if we can find out from chain information).

Users could also already be attempting to run customized software, enabling them to run proofs in a more distributed fashion than go-filecoin current can do itself.

I personally can run proofs in about 7 minutes on consumer hardware (i7-9700K CPU @ 3.60GHz)

**Comment by sywyn219** [comment]
Thank you very much for your answer. It seems that I still have to continue to study in depth.
