### ISSUE TITLE
[bug]Cannot running go-filecoin daemon completely

### ISSUE THREAD

**Issue by Cyanglacier** [filecoin-project/go-filecoin#2456]
**Describe the bug**
After installing 0.1.4 go-filecoin, running daemon and then will be stuck

**To Reproduce**
1. Run ./go-filecoin daemon
2. After sync 2 info, it will be stuck

**Screenshots**
https://ibb.co/GszT6J1

**Desktop (please complete the following information):**
 - OS: Ubuntu 64bit
 - Version: 18.04

**Comment by travisperson** [comment]
Can you show the full steps you took to get to this, such as the `go-filecoin init` call?

I'm a little confused because you have a call to `go-filecoin wallet balance` above, prior to starting the daemon. This call should not work without a daemon running, so it appears you already had a daemon running someplace.

**Comment by anorth** [comment]
@Cyanglacier could you let us know if you're still experiencing a problem? We'll assume you've figured it out and close this issue soon otherwise.

**Comment by rosalinekarr** [comment]
I'm closing this issue due to lack of response.

@Cyanglacier, if you're still having this problem, can you please reply with your exact initialization steps, and I'll reopen.
