### ISSUE TITLE
[bug]deal proposal contains no payment vouchers

### ISSUE THREAD

**Issue by AbelLaker** [filecoin-project/go-filecoin#2460]
**Describe the bug**

**To Reproduce**
2. Run this command '...'
3. See error
deal proposal contains no payment vouchers
**Expected behavior**

**Screenshots**
If applicable, add logging output or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Browser [if applicable, e.g. chrome, safari]

**Additional context**

**Comment by rkowalick** [comment]
@AbelLaker Thanks for filing an issue! Can you please fill out the template so we can better understand the problem better?

**Comment by rkowalick** [comment]
I have included the template below. Please reopen this issue once more info is available, and we'll be happy to take another look.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Run this command '...'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots or Console Output**
If applicable, add logging output or screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [if applicable, e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
