### ISSUE TITLE
error: failed to run custom build command for `filecoin-proofs v0.1.0 (/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs/filecoin-proofs)`

### ISSUE THREAD

**Issue by woshihanhaoniao** [filecoin-project/go-filecoin#2487]
### Description
error: failed to run custom build command for `filecoin-proofs v0.1.0 (/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs/filecoin-proofs)`
error: failed to run custom build command for `filecoin-proofs v0.1.0 (/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs/filecoin-proofs)`
process didn't exit successfully: `/home/lisheng/go/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs/target/release/build/filecoin-proofs-6b485da5c8a30024/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

/home/lisheng/go/src/github.com/filecoin-project/go-filecoin
cp: cannot stat 'proofs/rust-fil-proofs/target/release/paramcache': No such file or directory
cp: cannot stat 'proofs/rust-fil-proofs/target/release/paramfetch': No such file or directory
cp: cannot stat 'proofs/rust-fil-proofs/target/release/libfilecoin_proofs.a': No such file or directory
cp: cannot stat 'proofs/rust-fil-proofs/target/release/libfilecoin_proofs.pc': No such file or directory
Command './scripts/install-rust-fil-proofs.sh' failed: exit status 1
exit status 1

**Comment by rkowalick** [comment]
Thanks for the issue report. Could you include details below so we can investigate?

Please reopen this issue once more info is available, and we'll be happy to take another look.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Run this command '...'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots or Console Output**
If applicable, add logging output or screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [if applicable, e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
