### ISSUE TITLE
Cleaner paramfetch CLI

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#2488]
Paramfetch is a huge improvement to local parameter generation. But, it still takes a while to download large files, output is difficult to scan, and we still had a few users report they weren't sure where they were in the steps. These files are expected to get even larger, so let's take some time now to improve the paramfetch experience.

## Option 1 (Default)
Massively reduce the default log outputs, each step of paramfetch to 1 line. Only name specific files if an error occurs. 
"Checking for parameter files: 1 of 8"
"Downloading parameter files: 1 of 8"
"Validating parameter files: 6 of 8"
"Done"

The count would increment as each file completed, eg "1 of 8", "2 of 8", etc. For download in particular, it would be great to have a running percentage count since these files will get very large (not sure how much overhead that is to implement).

## Option 2 (Verbose mode)
Keep the same number of outputs, but make each step easier to scan and more specific.

1. Add counts to checks, downloads, and validation steps:
Each step should have a count and total.

2. Use sentence case and capitalize first line of each new step
This makes steps easier to scan, and follows common CLI conventions.
- "Checking X parameter files"
- "Checking:"
- "Does parameter file exist"

#### Examples:
**Old checking:**
checking: v10-vdf-post-c8ddc8e74f9c2ed6a4bc83df171a9e9e84e242cf6e48e20f71585106fa8a3ce6.vk
does parameter file exist... no

**New checking:**
Checking 1 of 8: v10-vdf-post-c8ddc8e74f9c2ed6a4bc83df171a9e9e84e242cf6e48e20f71585106fa8a3ce6.vk
Does parameter file exist? no

**Old fetching:**
fetching: v10-vdf-post-c8ddc8e74f9c2ed6a4bc83df171a9e9e84e242cf6e48e20f71585106fa8a3ce6
downloading parameter file... ok

**New fetching:**
Downloading 1 of 8: v10-vdf-post-c8ddc8e74f9c2ed6a4bc83df171a9e9e84e242cf6e48e20f71585106fa8a3ce6
Downloading... ok

## Option 3
Do both, use Option 1 by default and Option 2 for higher log level. (Summarizing from comments below, we want Option 3).

**Comment by mishmosh** [comment]
Tagging @rosalinekarr @anorth @dignifiedquire for feedback.

**Comment by porcuquine** [comment]
cc @sidke

**Comment by sidke** [comment]
i like option 3, we already have `--verbose` so we can pack the old style in there with proper formatting, and have the minimal output by default. open to feedback from other people who use it

**Comment by rkowalick** [comment]
@mishmosh Can you please use the story template?

**Comment by dignifiedquire** [comment]
I think something like this would be really nice 
![rec_v3](https://user-images.githubusercontent.com/790842/55507265-8da42880-5657-11e9-9766-0e5e39b3a6cd.gif)


Link to library https://github.com/a8m/pb

**Comment by anorth** [comment]
@sidke can we assign this one to you?

**Comment by mishmosh** [comment]
@mslipper is going to take this on. He's going to describe proposed technical approach in this issue for @sidke and @anorth to review.

**Comment by mslipper** [comment]
I took a look at the `paramfetch` code in `rust-fil-proofs`. The current implementation spawns a `curl` subprocess in `spawn_fetch_parameter_file`. Since it's likely that people with `curl` installed will also have `libcurl`, I suggest that we us a library such as [curl-rust](https://github.com/alexcrichton/curl-rust) and override the `progress_fn` to render a progress bar. I like the lib that @dignifiedquire suggested, so unless there are any strong objections we can use that one.

**Comment by mslipper** [comment]
@anorth does this sound reasonable to you?

**Comment by mslipper** [comment]
PR is open: https://github.com/filecoin-project/rust-fil-proofs/pull/628.

**Comment by anorth** [comment]
Thank you, sounds reasonable. cc @laser to coordinate with changes to paramfetch that allow easier control of which files to download. @mslipper may be able to assist with some development work there too?

**Comment by laser** [comment]
@mslipper - As per the words [written here](https://github.com/filecoin-project/rust-fil-proofs/pull/631), I had to revert your PR due to the downstream build issues it created. 

The TL;DR is that it's a non-zero amount of work to ensure that libcurl is installed in every environment in which we build go-filecoin (which links `libfilecoin_proofs.a`, which includes symbols from libcurl). The CircleCI containers don't have it, for example. This causes build breakages.

I'm going to re-open this issue. I appreciate the work you've done to get us the nice-looking progress bar, but we need either a solution which does not rely on libcurl or we need to coordinate this change with infra, the dev team, et cetera.
