### ISSUE TITLE
go-filecoin docker images install

### ISSUE THREAD

**Issue by fengchenggang1** [filecoin-project/go-filecoin#2494]
error: package github.com/filecoin-project/go-filecoin/build/*go: cannot find package "github.com/filecoin-project/go-filecoin/build/*go" in any of:

**Comment by rkowalick** [comment]
Thanks for the issue report. Could you include details below so we can investigate?

Please reopen this issue once more info is available, and we'll be happy to take another look.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Run this command '...'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots or Console Output**
If applicable, add logging output or screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [if applicable, e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by rkowalick** [comment]
Actually, this seems pretty clearcut.
