### ISSUE TITLE
clarifying/evolving plumbing/porcelain 

### ISSUE THREAD

**Issue by phritz** [filecoin-project/go-filecoin#2505]
@rosalinekarr's work in https://github.com/filecoin-project/go-filecoin/pull/2422 precipitates some interesting plumbing and porcelain questions, and separately @acruikshank is wrestling with placement of getactor in his message processing work. wrt to that he asked:
```
As I understand it, we’ve established the following rules:
1. porcelain only depends on plumbing
2. porcelain does not depend on other porcelain
3. plumbing does not depend on other plubming
...
```

My assumptions are different and the fact that https://github.com/filecoin-project/go-filecoin/blob/master/CODEWALK.md#plumbing-and-porcelain doesn't provide clear guidance on the issue means that there's a lot of room for error. 

the plumbing/porcelain pattern is an ever-evolving thing and we keep learning new details about how to apply it, and about mistakes we made that are clearer in hindsight. This issue is to add some more detail to how to use plumbing and porcelain, starting with a discussion. the output should be an update to codewalk or similar with our best understanding of how to apply the pattern.

## problems

here are some things that i think are sub-optimal with the current instantiation/direction:
- chain iteration is not provided as a core service in #2422 meaning implementation details like the cbor store leak pervasively all over the implementation anywhere someone wants to iterate the chain, eg https://github.com/filecoin-project/go-filecoin/pull/2422/files#diff-45355871e26f118ffda505d75e0c6bf0R61. seems like chain iteration needs to be a core service. 
- i see a lot of stuttering and really thing wrappers in plumbing around core apis, eg https://github.com/filecoin-project/go-filecoin/pull/2422/files#diff-87fea0f55f506cecb944302ba76d1149R13. i think we should avoid this pattern if possible in favor of just taking a the core api as a dependency to plumbing.
- very specific (instead of very general) calls are sometimes added to plumbing, eg https://github.com/filecoin-project/go-filecoin/pull/2422/files#diff-f5b6e9633a3e83fc7e236d40491b6402R146. when that happens i think we should treat it as a warning that something may be amiss... plumbing should be really generic with more specific porcelain on top.
- we should be careful about the effect triggered by putting something, call it foo, in porcelain. doing so 'pulls' anything that depends on foo up into porcelain as well. if we're not careful we will end up with many things that should really be plumbing in porcelain because of this, and duplicate calls at each level where the plumbing call is basically useless except to porcelain because it is missing the features of its porcelain version. a canonical example of this problem is with walletdefaultaddress. this call is in porcelain https://github.com/filecoin-project/go-filecoin/blob/ceda666240b5506ff546fccc3a19553bc276597b/porcelain/wallet.go#L44 which strictly speaking is maybe a good idea because it depends on plumbing calls only. however the effect is pernicious: anything that needs to use the default address suddenly must be porcelain. for example this caused a duplicate messagesend implementation to be pulled up into porcelain: https://github.com/filecoin-project/go-filecoin/blob/master/porcelain/message.go#L23. this version uses the default address whereas the plumbing version does not https://github.com/filecoin-project/go-filecoin/blob/master/plumbing/msg/sender.go#L72. the plumbing version is basically useless and we have twice as many messagesend calls as we need. walletdefaultaddress should be plumbing, and messagesend plumbing should use its implementation, and there should be no porcelain messagesend. i see this as an example of doing something kind of silly based on principle, and i think we should not do that.

## guidance?

here's what i think, please rip it up or add nuance as required:
- porcelain depends on plumbing or other porcelain implementations (i dont mean the porcelain api call, i mean the free function it calls into)
- plumbing depends on core apis or other plumbing implementations (i dont mean the plumbing.api calls, i mean the implementations eg msg.sender)
- avoid thin wrappers in plumbing, prefer to use the core api as a direct dependency
- use short names and do not stutter for plumbing packages, but also prefer fewer larger plumbing packages
- dont put gravity wells in porcelain (things like walletdefaultaddress that pull the world up with them), even if it means violating strict principles
- plumbing should be general purpose; porcelain can be very specific
- we should apply a high bar to inclusion in plumbing

also:
- chain iteration should be a core api and we should not leak implementation details like the cbor store all over the place (ie, there should be a way to get an iterator and iterate the chain without having to pass around cborstore; this probably means surfacing the state tree not just the root cid as part of chain iteration, or to add a getstatetree method or similar to the chain store).

whatchoo think? @acruikshank @anorth @rosalinekarr

**Comment by anorth** [comment]
Thanks @phritz, that is really helpful analysis and guidance and sounds good to me.

cc @ZenGround0 re chain iteration with respect to #2310 canonical block ordering in tipsets. This too should be a low level facility, although maybe just provided by the data types directly rather than explicitly in plumbing.

**Comment by anorth** [comment]
@phritz if you think you'll be able to author the CODEWALK changes summarising the guidance we end up with, could we assign this issue to you?

**Comment by acruikshank** [comment]
@phritz I agree with all your guidance. The only thing I question is whether we should let plumbing depend on plumbing. Certainly we should prefer cross-dependencies in porcelain over plumbing (e.g. if we A, B, and C to be in the API and A depends on B which depends on C, C should be plumbing and A and B should be porcelain).

Also, building on the point about no-thin wrappers in plumbing, I'd also like to question whether plumbing should have any "thick" wrappers either. Right now, we have some fairly complicated logic around message sending, querying, waiting and previewing in plumbing. The question is whether plumbing should own these important central processes or if it should merely expose processes implemented in core services to protocols, porcelain and the user. I lean towards the latter.

Right now message send and receive logic is split between `core`, `plumbing/msg`, and `node`. Messaging is important enough to be its own core service under a `message` package. `strgdls` and `cfg` logic could go in repo, `mthdsig` could go in the new `message` package, `dag` goes to `net`, and the plumbing API become nothing but a gatekeeper for exposing core service methods.

Part of the motivation for this is that core services should be able to access this functionality. The fact that they can't depend on the plumbing API will encourage us to move functionality into the API that doesn't belong there. I think this plays a part in the gravity well problem.

**Comment by rosalinekarr** [comment]
> chain iteration is not provided as a core service in #2422 meaning implementation details like the cbor store leak pervasively all over the implementation anywhere someone wants to iterate the chain, eg https://github.com/filecoin-project/go-filecoin/pull/2422/files#diff-45355871e26f118ffda505d75e0c6bf0R61. seems like chain iteration needs to be a core service.

@phritz, my understanding was that removing chain iteration from the core was one of the goals of issue #1847. Specifically, you recommended in [this comment](https://github.com/filecoin-project/go-filecoin/issues/1847#issuecomment-461966992) removing the `BlockHistory` method from chain package.

I'm also not convinced that the core needs to own chain iteration beyond the `GetHead` and `GetNext` methods. Regarding the example you provided in plumbing, I'm not sure i see the problem with passing the cbor store as a dependency to `MsgSender` package, especially since the `MsgPreviewer`, `MsgQueryer`, and `MsgWaiter` packages each already accept the cbor store as an initialization argument. My understanding of plum-pork was that part of it's explicit goals is to wrap the non-user-friendly and potentially dangerous core package interfaces with a user-friendly and (relatively) safe API. Notably, these plumbing modules are also the only places the cbor store is exposed, since every occurrence of chain iteration above plum-pork uses the `ChainLs` plumbing method, and every use of it below plum-pork is in the core api for chain itself, which already has and must have access to the cbor store.

I do recognize an issue in that the chain package's `CollectTipSetsOfHeightAtLeast` and `CollectAtMostNTipSets` methods use `GetNext` in a repetitive manner, but my hope was to resolve this in a follow up PR to #2422 which moves some of their functionality into plumbing. Specifically, the only place these methods are actually used (and not just passed to something else) is in the `SampleChainRandomness` method in `vm/context.go` which is already exposed through a porcelain API method of the same name. This porcelain doesn't actually use any plumbing, so my thought was that it could be pulled down to the plumbing level, and any necessary dependencies in the chain package could be pulled up into it. This would leave a single `Random` method on the chain plumbing which can be passed to the VM for processing or used elsewhere for generating deterministic randomness from the chain state.

> i see a lot of stuttering and really thing wrappers in plumbing around core apis, eg https://github.com/filecoin-project/go-filecoin/pull/2422/files#diff-87fea0f55f506cecb944302ba76d1149R13. i think we should avoid this pattern if possible in favor of just taking a the core api as a dependency to plumbing.

I'm weary of exposing the chain's core api through plumbing directly, as it would mean necessarily include mutative methods such as `HandleNewTipset` or `SetHead` in plumbing. My understanding of plum-pork was that one of the state goals was to avoid exposing dangerous methods and to provide a safe interface for the command and protocol layers to invoke thereby reducing the risk of accidentally exposing security vulnerabilities in these higher layers and hopefully preventing us from further muddying the waters of separation of concerns in the application.

> very specific (instead of very general) calls are sometimes added to plumbing, eg https://github.com/filecoin-project/go-filecoin/pull/2422/files#diff-f5b6e9633a3e83fc7e236d40491b6402R146. when that happens i think we should treat it as a warning that something may be amiss... plumbing should be really generic with more specific porcelain on top.

I was hoping to address this specific example in the chain randomness follow up PR i mentioned earlier, but i totally agree that this is quickly becoming a problem in other places with the currently plum-pork implementation.

> we should be careful about the effect triggered by putting something, call it foo, in porcelain. doing so 'pulls' anything that depends on foo up into porcelain as well. if we're not careful we will end up with many things that should really be plumbing in porcelain because of this, and duplicate calls at each level where the plumbing call is basically useless except to porcelain because it is missing the features of its porcelain version. a canonical example of this problem is with walletdefaultaddress. this call is in porcelain
go-filecoin/porcelain/wallet.go
Line 44 in ceda666
 func WalletDefaultAddress(plumbing wdaPlumbing) (address.Address, error) { 
which strictly speaking is maybe a good idea because it depends on plumbing calls only. however the effect is pernicious: anything that needs to use the default address suddenly must be porcelain. for example this caused a duplicate messagesend implementation to be pulled up into porcelain: https://github.com/filecoin-project/go-filecoin/blob/master/porcelain/message.go#L23. this version uses the default address whereas the plumbing version does not https://github.com/filecoin-project/go-filecoin/blob/master/plumbing/msg/sender.go#L72. the plumbing version is basically useless and we have twice as many messagesend calls as we need. walletdefaultaddress should be plumbing, and messagesend plumbing should use its implementation, and there should be no porcelain messagesend. i see this as an example of doing something kind of silly based on principle, and i think we should not do that.

Totally agree. We need to be very careful about overly decomposing plumbing calls. My rule of thumb so far has been that any methods which can be composed entirely from calls to just one plumbing package should probably be moved into that plumbing package and it's dependent calls should be replaced with private methods shared between the public methods on said package. Porcelain should strictly only compose calls between separate plumbing packages.

Unfortunately, this strategy doesn't resolve the issues with `MessageSend` and `MessageSendWithDefaultAddress`, but with regard to that case specifically, I'm beginning to think that `MessageSendWithDefaultAddress` simply shouldn't exist, and that any invocations of it should just call `WalletDefaultAddress` first and pass the result to `MessageSend`. This seems especially evident in the fact that several calls to `MessageSendWithDefaultAddress` never provide a nil address at all. Most of the necessity for `WalletDefaultAddress` comes in the commands layer where we use it as a safe guard against incomplete user options passed in through flags, so it might make more sense as a commands helper.

> porcelain depends on plumbing or other porcelain implementations (i dont mean the porcelain api call, i mean the free function it calls into)

I agree with the dependencies here, but i'm not sure that any porcelain should call other porcelain functions directly, since that would break our current approach of building interfaces over the porcelain API which seems highly beneficial for testing and encapsulation of plumbing packages.

> plumbing depends on core apis or other plumbing implementations (i dont mean the plumbing.api calls, i mean the implementations eg msg.sender)

I agree with @acruikshank here that I don't think plumbing should depend on other plumbing, otherwise I start to question where the lines between plumbing and porcelain are anymore, since we could just as easily build every method in plumbing and let each plumbing package depend on every other plumbing package.

> avoid thin wrappers in plumbing, prefer to use the core api as a direct dependency

This makes sense to me in cases where we don't expose too much of the underlying core api.

> use short names and do not stutter for plumbing packages, but also prefer fewer larger plumbing packages

:+1:

> dont put gravity wells in porcelain (things like walletdefaultaddress that pull the world up with them), even if it means violating strict principles

I agree that we need to avoid pulling too much into the porcelain level, but I suspect if not doing so means violating the principles we've laid out for plum pork, that's an indication that something much larger is probably wrong. In the case of default address, I suspect the problem is that we're composing calls at too low a level and attempting to do too much with a single method call. Extracting this particular call up to its corresponding call sites makes this especially clear since it's rarely actually needed and, once we assume the function arguments passed to `MessageSend` are already valid, the code therein becomes much cleaner.

> plumbing should be general purpose; porcelain can be very specific

:+1:

> we should apply a high bar to inclusion in plumbing

Agreed. I think this bar should be 1) necessary for the commands and/or protocol layers, 2) reusable (maybe the old rule of three?) and 3) does not expose any internals of the core layer.

> Also, building on the point about no-thin wrappers in plumbing, I'd also like to question whether plumbing should have any "thick" wrappers either. Right now, we have some fairly complicated logic around message sending, querying, waiting and previewing in plumbing. The question is whether plumbing should own these important central processes or if it should merely expose processes implemented in core services to protocols, porcelain and the user. I lean towards the latter.

@acruikshank, I believe moving some of the "thick" method calls in plumbing to the core level will necessarily imply breaking separation of concerns. For example, the current `Actr` plumbing makes use of the `state` package, the `exec` package, the chain reader and the the cbor store, so, to move this into the core layer, we would need choose one of these core packages to become dependent on all the other packages, which feels like a violation of separation of concerns. Alternatively, we could create a new `actr` core package which depends on the other packages, but at that point, we're just building plumbing exactly as it is except in a different directory.

> Right now message send and receive logic is split between core, plumbing/msg, and node. Messaging is important enough to be its own core service under a message package.

Can you elaborate? I'm not sure what aspect of `MessageSend` lives in the node anymore, and I'm not sure I see a problem with it being split between core and plumbing, since plumbing's purpose is to wrap core functionality. Also, how would moving messaging into a core package be any different from the current plumbing implementation except in which directory we put it in?

> strgdls and cfg logic could go in repo

This seems like we would be putting too much responsibility on `repo`. imo, repo serves as an abstract manager for the repodir on disk (or in-memory for test), and any logic regarding the specific state stored in the repo should be handled in the package where that state is defined. Otherwise, repo becomes dependent on the specific implementations of every other package in the project which store state to disk.

> mthdsig could go in the new message package

`mthdsig` no longer exists.

> dag goes to net

I really don't think `dag` should have anything to do with `net`, since it doesn't have anything to do with sending or receiving data on the network, and it doesn't share any dependencies with `net`.

> and the plumbing API become nothing but a gatekeeper for exposing core service methods.

I don't really see the advantage of turning plumbing into a glorified interface for the core api. Doing so seems like it would put us right back where we started before the plum pork refactor, with tons of complex dependencies between packages and a single god object (now the core api instead of the the node api) in charge of basically everything.

> Part of the motivation for this is that core services should be able to access this functionality. The fact that they can't depend on the plumbing API will encourage us to move functionality into the API that doesn't belong there. I think this plays a part in the gravity well problem.

I think you're addressing a different gravity well here. @phritz was talking specifically about things being pulled into the porcelain api from the plumbing api, but I think you're talking about things being pulled into the plumbing api from the core api, which i don't think is a necessarily bad thing. As I see it, the plumbing api is _supposed to_ pull things out of the core api and encapsulate them in well-documented, self-contained, user-friendly packages with clearly defined dependencies that can be more easily mocked and tested.

Since we all seem to have some differing ideas about how plum-pork is supposed to work, I'll just layout a quick diagram of how I've been thinking about it:

```
Porcelain <--- The "helper" layer of go-filecoin, where we compose plumbing
               method calls and certain core method calls into even more useful
               methods which handle common, self-contained tasks and are
               frequently used in the commands layer or by the protocol. Like
               the plumbing layer, nothing should live in porcelain that does
               not provide useful functionality to the user. Porcelain methods
               can and should make use of other porcelain methods using
               interfaces for easier testing and modularity. Porcelain methods
               should also use plumbing methods from at least two separate
               plumbing packages. If a porcelain method doesn't use any plumbing
               at all, it likely belongs a level above in the command or
               protocol layer. If a porcelain method uses methods from only one
               plumbing package, it likely belongs a level below in said
               plumbing package, and any functionality it shares with other
               plumbing methods should be extracted to private methods.
================================================================================
Plumbing  <--- The "public" layer of the go-filecoin, where core methods are
               composed to build useful interfaces that users can interact with.
               Nothing should live in plumbing that does not provide useful
               functionality to the end user. Plumbing packages should only
               depend on core packages and *never* depend on other plumbing
               packages. If a plumbing method needs to use another plumbing
               method from the same package, these methods should share
               functionality through private methods within their package. If a
               plumbing method needs to use a plumbing method from another
               package, the method in question should live at the porcelain
               level instead.
================================================================================
Core      <--- The "meat" of the go-filecoin where state is mutated, work is
               done, and external dependencies are utilized. None of these
               methods should *ever* be exposed to the commands layer and should
               only sparingly be exposed to the protocols. Additionally, core
               packages should be self-contained when possible and should not
               depend on other core packages, however exceptions may occur.
```

**Comment by phritz** [comment]
thanks for the thorough writeups and thoughtful exploration of the topic

>  I'd also like to question whether plumbing should have any "thick" wrappers either. Right now, we have some fairly complicated logic around message sending, querying, waiting and previewing in plumbing. The question is whether plumbing should own these important central processes or if it should merely expose processes implemented in core services to protocols, porcelain and the user. I lean towards the latter.

that's a really good point, and i buy it. plumbing should probably just be really thin wrappers and any significant functionality implemented in core. rose points out that this will likely require some hard choices or perhaps might be impossible in some cases due to the way dependencies work. that seems likely, but in my mind that might argue for defactoring packages into larger units. our core packages are much too granular as it is, and many of them dont actually do anything on their own. i'd support exploring this direction.

> @phritz, my understanding was that removing chain iteration from the core was one of the goals of issue #1847. Specifically, you recommended in this comment removing the BlockHistory method from chain package.

removing iteration from the *chain store interface* was a goal, not removing it from the chain package. a key sentence that follows the new definition in https://github.com/filecoin-project/go-filecoin/issues/1847#issuecomment-461966992 is "...plus a chain iterator thingy that uses the above but is not in the interface like blockhistory". The observation is that if we have an interface like the one articulated that allows you to get the head tipset cids, and then get tipsets, you dont need anything else in the interface itself to support iteration. you can provide a helper -- an iterator thingy, which we now know is https://github.com/filecoin-project/go-filecoin/blob/master/chain/traversal.go -- that lives outside the interface, that uses it. Like the iterator given in traversal.go.

the primary thing i think we need to do is figure out what happens to https://github.com/filecoin-project/go-filecoin/pull/2422. i think the right thing to do is to break it up into a series of smaller prs that stand on their own and can be understood on their own. as it is, there's too much changing for any one person to wrap their head around. whether we want to pay the price to do the right thing is another question. i understand it will be more work and more frustrating to break a large pr up into separate pieces. what's your sense, @rosalinekarr ?

the next thing we need to do is discuss the many points rose brings up in her previous comment. I think perhaps might be best to call out places where assumptions or opinions differ, which are many. Let me attempt to do that and meanwhile we should actively try to connect synchronously to talk these things through, I will try in the next few mornings to find a good time. if we do talk sync then we will reflect the outcome of that conversation here.

regarding specifics:

- why not pass cborstore around? because it is only used to fetch state tree, which is a service an existing thing could provide, or we could just provide the data directly, and then the world doesn't have to know about this implementation detail. what we are doing now is the equivalent of providing a partially-loaded db-backed model object along with a database handle to everything that needs the model object -- so that you can fetch the rest of the model object with the database handle if you need it. why not just pass the fully loaded model object, or have the object know how to load itself (eg, activerecord)? the fact that all the code has the pattern of passing the cbor store around is not an argument that it is a good pattern. 

- "I'm weary of exposing the chain's core api through plumbing directly, as it would mean necessarily include mutative methods such as HandleNewTipset or SetHead in plumbing." -- i dont think this is necessary at all, and as you say would not be good. when i say 'just take the core api as a dependency to plumbing' i mean like the way chain https://github.com/filecoin-project/go-filecoin/blob/e3f7439e2ac63e555820a8ec7e0b290974042786/plumbing/api.go#L64 or message pool https://github.com/filecoin-project/go-filecoin/blob/e3f7439e2ac63e555820a8ec7e0b290974042786/plumbing/api.go#L68 are taken as direct depenencies. plumbing calls are simply delegated to the dependency eg https://github.com/filecoin-project/go-filecoin/blob/e3f7439e2ac63e555820a8ec7e0b290974042786/plumbing/api.go#L125. i dont see any need to expose private/dangerous calls in this fashion.

- "Porcelain should strictly only compose calls between separate plumbing packages." -- I'm not sure i would agree. i would imagine porcelain can compose calls across whatever plumbing packages it likes, including calls in a single package. please keep in my the feedback given elsewhere about pushing complexity into callers and out of fundamental (core) apis. given a choice between more code in porcelain and more code in plumbing we would choose more in porcelain any day of the week. i'll quote the discussion below.

- regarding messagensedwithdefault, it does seem like the default address is a fundamental concept that should live in plumbing. walletdefaultaddress makes sense to me. if you want to do away with the default-using version of messagesend that'd be fine by me, see philosophy on pushing complexity into callers. but also i do not feel super strongly about this case.  

- "I agree with the dependencies here, but i'm not sure that any porcelain should call other porcelain functions directly, since that would break our current approach of building interfaces over the porcelain API which seems highly beneficial for testing and encapsulation of plumbing packages." -- i don't see why it would break our current approach. if porcelain A calls porcelain B then porcelain A's dependencies are the union of A and B's plumbing dependencies. doesn't break anything i dont think.

- " I don't think plumbing should depend on other plumbing, otherwise I start to question where the lines between plumbing and porcelain are anymore, since we could just as easily build every method in plumbing and let each plumbing package depend on every other plumbing package." -- except that plumbing is supposed to be minimal and orthogonal and if you start stuffing everything into it you lose these properties. i think you are missing the design aesthetic going into plumbing: it's not just a place to put stuff, it's the small set of calls that comprise "the" filecoin api to the user. that rule is as important as all the others. it should be small and understandable and useful.

> I don't really see the advantage of turning plumbing into a glorified interface for the core api. Doing so seems like it would put us right back where we started before the plum pork refactor, with tons of complex dependencies between packages and a single god object (now the core api instead of the the node api) in charge of basically everything.

this is a **really important** thing to align on. plumbing **is** an interface to the core api. it is the set of public calls that you need to build most user- and tool-facing features. it is a narrow, flattened view of the core api, aggregated for convenience and understandability. it should be small and orthogonal and general. this does not in any way put us back to the place we were before the refactor because:
- the plumbing api is not in charge of anything; the core apis own the data and are in charge of it; the plumbing api merely provides a convenient interface to those things
- having the plumbing api means that higher level stuff like protocols or commands *don't have to worry about the complex relationships between core apis*, they just depend on the plumbing. it abstracts away a lot of complexity and frees higher level code from having to take a zillion individual dependencies that might change on a frequent basis.
- the core apis that plumbing delegates implementation to can and do exist independently of each other. they can be instantiated  on their own and unit tested because they take their dependencies. contrast this with the node api world where the implementation of every call is the node, a huge complicated object that requires a lot of set up and the individual calls of which cannot be easily unit tested. 

the plumbing api is not a god object, its an aggregation of a bunch of core functionality that looks like the node api in the sense that it supports a lot of calls, but has none or rather few of the downsides of the actual god object we had. (i cover this in the second half of https://github.com/filecoin-project/go-filecoin/issues/1469#issuecomment-448707607)

> the plumbing api is supposed to pull things out of the core api and encapsulate them in well-documented, self-contained, user-friendly packages with clearly defined dependencies that can be more easily mocked and tested.

I don't think i agree. i think it could work that way, but the direction ac is articulating is different: have plumbing be just a view on core apis.

i'm glad you call out the different levels at the end of your comment because we should do some more workshopping of these concepts. in particular my view is more consistent with https://github.com/filecoin-project/go-filecoin/blob/master/CODEWALK.md#core-services:
  - core owns state but does not drive state changes. protocols drive state changes in core. core has private methods like sethead that are selectively provided to protocols. core has public methods like gethead which are liberally provided via the plumbing interface. core components dont really do much on their own, they need to be driven by protocols or users (or users via protocols)
  - plumbing is a convenience set of calls that use public core apis to serve most user- and protocol- and tool-facing needs. plumbing is small and general purpose and understandable and orthogonal. 
  - porcelain is convenience compositions of plumbing (and maybe other porcelain) calls. porcelain, like plumbing, is ephemeral, it doesn't really have state itself. 

----- 
regarding good apis:
```
there are a lot of considerations for how to define good apis but here
are a few generalizations it is hard to go wrong with: 1. push complexity 
onto the caller side of the api; generally dont provide convenience functions 
if your callers could. 2. keep your apis as small as possible 3. keep your calls 
as orthogonal as possible. .... having apis that follow these principles make
the api easier to optimize, easier to understand, and easier to satisfy with a
variety of implementations. they limit the blast radius of changes, should you 
have to make them. martin fowler, one of the gang of four, identifies this
philosophy of api design as the minimal interface and articulates some of its benefits 
here https://martinfowler.com/bliki/MinimalInterface.html.  this is in contrast 
with sprawling expansive convenience interfaces he calls humane interfaces 
https://martinfowler.com/bliki/HumaneInterface.html. the systems and distributed 
systems worlds are strongly oriented around minimal interfaces these days for the 
reasons articulated above. many web frameworks eg rails are oriented around the 
latter in the name of developer productivity. 
```

**Comment by rosalinekarr** [comment]
> that's a really good point, and i buy it. plumbing should probably just be really thin wrappers and any significant functionality implemented in core. rose points out that this will likely require some hard choices or perhaps might be impossible in some cases due to the way dependencies work. that seems likely, but in my mind that might argue for defactoring packages into larger units. our core packages are much too granular as it is, and many of them dont actually do anything on their own. i'd support exploring this direction.

This sounds fine to me, but I want to be careful about maintaining some rules around dependencies in the project. I think our current dependency rules have helped a lot in enforcing patterns that are more easily mocked and, as a result, more easily tested. We can probably reformulate or lax our current rules a bit, but I just don't want to wind up in a situation like the old test node, where unit testing certain packages becomes impossible without including a huge chunk of the rest of the project.

> removing iteration from the chain store interface was a goal, not removing it from the chain package. a key sentence that follows the new definition in #1847 (comment) is "...plus a chain iterator thingy that uses the above but is not in the interface like blockhistory". The observation is that if we have an interface like the one articulated that allows you to get the head tipset cids, and then get tipsets, you dont need anything else in the interface itself to support iteration. you can provide a helper -- an iterator thingy, which we now know is https://github.com/filecoin-project/go-filecoin/blob/master/chain/traversal.go -- that lives outside the interface, that uses it. Like the iterator given in traversal.go.

:+1:, thx for pointing it out. I didn't notice we had added `chain/traversal.go`

> the primary thing i think we need to do is figure out what happens to #2422. i think the right thing to do is to break it up into a series of smaller prs that stand on their own and can be understood on their own. as it is, there's too much changing for any one person to wrap their head around. whether we want to pay the price to do the right thing is another question. i understand it will be more work and more frustrating to break a large pr up into separate pieces. what's your sense, @rosalinekarr ?

I think, after addressing the feedback on #2422 and a little bit of clean up, I can get the size of the PR down a bit, especially since `traversal.go` will let me throw away a bunch of code. I can take a shot at it, and if the PR isn't more reviewable by the time I'm done, I can split it up.

> "I'm weary of exposing the chain's core api through plumbing directly, as it would mean necessarily include mutative methods such as HandleNewTipset or SetHead in plumbing." -- i dont think this is necessary at all, and as you say would not be good. when i say 'just take the core api as a dependency to plumbing' i mean like the way chain

:+1:, makes sense

> "Porcelain should strictly only compose calls between separate plumbing packages." -- I'm not sure i would agree. i would imagine porcelain can compose calls across whatever plumbing packages it likes, including calls in a single package. please keep in my the feedback given elsewhere about pushing complexity into callers and out of fundamental (core) apis. given a choice between more code in porcelain and more code in plumbing we would choose more in porcelain any day of the week. i'll quote the discussion below.

Sorry, I don't think i was clear enough in my earlier comment. I don't mean to say that porcelain strict cannot depend on only one plumbing package, just that when it does that's typically and indication that the porcelain itself could be contained in the plumbing itself. It's just a code smell. For example, we currently have a `SampleChainRandomness` method in porcelain who's only dependency is a single plumbing method, `GetRecentAncestorsOfHeaviestChain`, which probably shouldn't be plumbing anyway. In this case, `SampleChainRandomness` should probably be the actual plumbing method, and `GetRecentAncestorsOfHeaviestChain` should only be in the core api.

> regarding messagensedwithdefault, it does seem like the default address is a fundamental concept that should live in plumbing. walletdefaultaddress makes sense to me. if you want to do away with the default-using version of messagesend that'd be fine by me, see philosophy on pushing complexity into callers. but also i do not feel super strongly about this case.

:+1:

> "I agree with the dependencies here, but i'm not sure that any porcelain should call other porcelain functions directly, since that would break our current approach of building interfaces over the porcelain API which seems highly beneficial for testing and encapsulation of plumbing packages." -- i don't see why it would break our current approach. if porcelain A calls porcelain B then porcelain A's dependencies are the union of A and B's plumbing dependencies. doesn't break anything i dont think.

I think my intent here is that we should try to keep dependencies minimal when possible. That means we have less to mock out in tests and less code to change when modify a dependency upstream. In the A/B example if the A porcelain method has several other dependent methods, and the B porcelain method's only dependent method is A, including all of A's dependencies in B's deps interface would imply mocking all of those function in B's test and double testing A's functionality in B's test. This could get especially dicey when A has side effects or mutates state, because now B's test needs to allow for that.

> " I don't think plumbing should depend on other plumbing, otherwise I start to question where the lines between plumbing and porcelain are anymore, since we could just as easily build every method in plumbing and let each plumbing package depend on every other plumbing package." -- except that plumbing is supposed to be minimal and orthogonal and if you start stuffing everything into it you lose these properties. i think you are missing the design aesthetic going into plumbing: it's not just a place to put stuff, it's the small set of calls that comprise "the" filecoin api to the user. that rule is as important as all the others. it should be small and understandable and useful.

I understand the design goal of plumbing. I'm saying that if a plumbing package depends on another plumbing package to do work, that seems like the first plumbing package should just be porcelain. It may not be absolutely true, but it feels like another code smell. Otherwise, I'm not sure the distinction between plumbing and porcelain is clear anymore. As I understand it, porcelain is decoration on top of plumbing. It takes simple core api methods, composes them, and adds a little extra functionality for ease of use. If a plumbing package is adding extra functionality on top of another plumbing package, it seems like said plumbing package fits the definition of porcelain.

> this is a really important thing to align on. plumbing is an interface to the core api. it is the set of public calls that you need to build most user- and tool-facing features. it is a narrow, flattened view of the core api, aggregated for convenience and understandability. it should be small and orthogonal and general.

Sorry, I think I misspoke again. I *do* think plumbing should be an interface for the underlying core api, but I don't think it should *only* be that. I think we've created something very helpful in the dependency structure of plumbing and porcelain that significantly improves testing and makes the code easier to change without falling into a dependency hell where changing a single package means needing to significantly change dozens of other dependent packages.

My worry with moving all functionality into the core api then turning plumbing into a big delegator pattern over it all is that we could end up creating dependencies between core packages that become more and more tangled as time goes on. Eventually, I think this could put us in a situation a lot like where we were with the old offline test node, when lots of core api tests depend on a huge section of the rest of the application to work. I realize this isn't quite as bad as things were with the old node, but it still feels like a step in the wrong direction.

As long as we can establish some rules to avoid core api turning into a big ball of mud, I'm comfortable with stripping all logic out of the plumbing api, but I think we'll need to be very careful in our work going forward to more effectively use interfaces and to avoid creating hard links between packages that don't need to exist. Ideally, I think every core package should be entirely self-contained and only composed at the plumbing and porcelain layers, but I realize that may be a bit too idealistic.
