### ISSUE TITLE
Cleanly separated networks (DHT, pubsub, ...)

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#2532]
This epic collects multiple issues around the topic of cleanly compartmentalizing networks and their DHTs. Whoever works on this, please propose a set of changes to resolve them as a group: #1700, #2357, #2421, #2426

**Comment by anorth** [comment]
I believe that we're gaining useful information from the unintentional "attacks" by our old network on the new one each time we restart the user devnet. I propose that we push back fixing this for a while so that we can continue learning and fixing underlying issues.

I do think we will still want to make this separation around the time of launching a long-lived testnet though.

**Comment by anorth** [comment]
Deleting this epic now after removing all the issues from it. Most were subsumed by network names (as part of protocol upgrade work).
