### ISSUE TITLE
[bug] Paramcache is not included in the binary release

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2541]
**Describe the bug**
Paramcache is not included in the binary release. This means the release is not usable if the parameters cannot be fetched with the included `paramfetch`.

**Expected behavior**
Paramcache is included in the release binary

**Version information**
Since release 0.1

**Additional context**
Reported [here](https://filecoinproject.slack.com/archives/CEGN061C5/p1554882813021400)

See also #1913, which was in a different context and I think thought to be resolved by `paramfetch`.

**Comment by porcuquine** [comment]
Eventually `paramcache` will not be viable concept because it will not be possible to generate them.

In order for this eventual change not to seem like a major problem, we should stop supporting parameters anyone can generate as soon as possible. Instead, everyone should require the single set of parameters which have been published.

The only reason not to do this sooner is that we still believe we need to run `paramache` (because I guess people have a hard time downloading). Please note that generating parameters is also going to become less practical. (In general, you can only generate parameters half as large as those you can actually use — for a given amount of RAM.)

So I would like to make the argument that providing *more* support for running `paramcache` may be counter-productive.

I think we should feel the pain every time someone has to run this (if only in their time to generate). If we try to make it less painful, that will only encourage us not to de-support sooner. But I think we should desupport as soon as possible.

I'm not opposed to the proposed work being performed, but I wanted to record this reasoning — because I may partially or completely disagree with the logic behind performing it. With that said, you should do whatever makes most sense for this stage of the devnets.

**Comment by anorth** [comment]
Thank you. @porcuquine and I chatted and are in agreement that for the real networks, when launched, parameter generation will not be possible because the parameters will rely on a trusted setup – download will be the only way.

However, before those networks, and possibly even afterwards, parameter generation is useful for development. We can expect all such users to be working from source in the future. We have some functionality to add to paramfetch to support multiple sector sizes etc in the future, but I can see paramcache being removed from binary releases closer to mainnet.
