### ISSUE TITLE
Abstract interface to time for faster and precise tests

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2550]
### Description
Numerous parts of our code sleep, waiting for real time to elapse before moving on. This dependency on real "wall clock" time complicates and slows down testing. In particular:
- sleeps executed while testing waste developer time and increase the memory footprint of concurrent tests
- it's hard to reliably test things that sleep since the passage of time cannot be precisely controlled
- it's hard to arrange specific timestamps for code that inspects them
- it's hard to orchestrate interleavings of concurrent processes without control over their view of time

A widely used pattern for improving this is to present an abstract interface to time as a `Clock` and inject a clock into any code that needs reference to it. Sometimes the ideas of observing the current instant of time and of delaying for a particular duration are distinct, and sometimes coupled, but both can be injected and controlled from the outside. At production runtime, a `SystemClock` implements the methods via `time` builtins.

This issue proposes finding or writing an abstract clock and/or delay interface and removing all direct uses of methods such as `time.Sleep` and `time.Now` with method calls. Tests can then directly drive the passage of simulated time with zero actual sleeps, and it will also become possible to test the interaction of nodes that have a different view of time.

This pattern will likely work for unit and in-process integration tests, but not (forked) daemon tests. We should come to prefer in-process tests in many cases for their superior speed.

### Acceptance criteria
- No unit or in-process integration test paths sleep or observe real wall-clock time

### Where to begin
Some inspiration:
- [Java SDK Clock](https://docs.oracle.com/javase/8/docs/api/java/time/Clock.html)
- A [Go clock implementation](https://github.com/jmhodges/clock)

Begin with survey of the current paths to `Sleep` or other clock-referencing functions.

**Comment by travisperson** [comment]
[TestBootstrapperStartAndStop](https://github.com/filecoin-project/go-filecoin/blob/master/net/bootstrap_test.go#L28) is a good example of this. Anywhere we use a ticker in packages could benefit from using a mocked clock for testing. In this example we use the ticker to run our `Bootstrap` method (which is used to ensure our lower water mark for peers) on a periodic interval.

**Comment by frrist** [comment]
All tests that sleep can be found with the command:
`find . -name '*_test.go' | rg -v "daemon" | xargs rg -l Sleep` they are as follows:
```
./protocol/hello/hello_test.go
./proofs/sectorbuilder/testing/interface_test.go
./node/message_propagate_test.go
./node/block_propagate_test.go
./net/bootstrap_test.go
./node/node_test.go
./plumbing/msg/waiter_test.go
./tools/fast/tests/retrieval_test.go
```

There appear to be a few different reasons for sleeps in our tests:

#### Waiting for the network connection notifications to propagate:
`./protocol/hello/hello_test.go`
`./node/message_propagate_test.go`
`./node/block_propagate_test.go`
`./node/node_test.go`

I believe this is a limitation of libp2p, as I understand the network connection notifications happen async. I am not sure a time abstraction can help us here -- open to ideas (gut says this change needs to happen on the libp2p side such that connection notification can happen synchronously). 

#### Waiting for nodes to sync their chains
`./node/block_propagate_test.go`

This sleep exists because we are waiting for a message/block to propagate over pubsub to other in process nodes. I think a reasonable solution here is to make the [processBlock and processMessage](https://github.com/filecoin-project/go-filecoin/blob/7b215c7df8e578ab26ed875740ff0fac4154485c/node/node.go#L535-L536) function pluggable for easier testing. 

#### Waiting for a ticker to `tick` (@travisperson has already pointed this out above)
`./net/bootstrap_test.go`

This test seems well suited for a time interface or similar.

#### Not Needed:
`./plumbing/msg/waiter_test.go`

I'll admit I'm having a hard time parsing this tests, but I ran it 10,000 times without a sleep and couldn't get it to flake, I think the wait groups are adequate -- sleep could probably be removed 

#### Not sure
`./proofs/sectorbuilder/testing/interface_test.go`

I am not sure why this sleep is needed, @laser could you weigh in on this?

**Comment by anorth** [comment]
As part of block timestamp validation work, we now have a `Clock` interface. I'll close this issue, as actually using that interface in various places should be motivated by immediate needs.
