### ISSUE TITLE
[bug] Cannot get FIL by following the instructions of Section "Get FIL from the Filecoin faucet" in Get Started

### ISSUE THREAD

**Issue by SCUTVincent** [filecoin-project/go-filecoin#2560]
**Describe the bug**

Cannot get FIL by following the instructions of Section "Get FIL from the Filecoin faucet" in Get Started
**To Reproduce**
I can start "go-filecoin daemon" and get wallet addr and message CID.
But no response for a long time by "go-filecoin message wait ${MESSAGE_CID}".
Also, return 0 by "go-filecoin wallet balance ${WALLET_ADDR}"

**Expected behavior**
Should return non-zero FIL.

Can anyone provide me some advice?

**Comment by travisperson** [comment]
When you use the faucet to receive funds, we are send you funds from another node. The funds are issued as a message which will be mined into a new block. You need that block synced to your chain before your node can determine that you wallet has the balance. The `message wait` command is used to ensure that the message is 1) mined into a block 2) that you have that block synced to your chain.

Currently chain syncing can be a little slow. The process of downloading all of the block is pretty quick, the slowness comes when your node replays all messages in the block to ensure everything is valid. This process currently takes quite a long time. You can compare your nodes current block height with the networks by running the command below. It will provide you some information about your current chain head. 

```
$ go-filecoin show block $(go-filecoin chain | head -n1)
```

You can compare that to the value at https://stats.filecoin.io. If you look at the stats chain head prior to using the faucet, you can use that value to help determine how close you are to having the correct block to allow you to start using the funds in your wallet. Due to the slowness of processing blocks at the moment, having this number in mind can be helpful, as by the time you run into the block with your message, the chain might be another 1000 blocks past it.

**Comment by rosalinekarr** [comment]
@SCUTVincent, have you received your FIL yet?

**Comment by SCUTVincent** [comment]
> @SCUTVincent, have you received your FIL yet?

Not yet. The block syncing time is very very long. I am still awaiting it to be finished.

**Comment by rosalinekarr** [comment]
@SCUTVincent, can you run the following command and paste the output here?

```
go-filecoin chain head
```

**Comment by SCUTVincent** [comment]
root@it-System-Product-Name:~/Desktop/ifps/filecoin# go-filecoin show block zDPWYqFD4onJUygV8qNkPB5kh2J9ZQydjqwJW9EiMG2qqYGogJk5
Block Details
Miner:  t2dqagdc3tudvfhvce7cj5ep6scfmvtuyhfjc3vra
Weight: 179303.345
Height: 22316
Nonce:  0
root@it-System-Product-Name:~/Desktop/ifps/filecoin#

**Comment by SCUTVincent** [comment]
> @SCUTVincent, can you run the following command and paste the output here?
> 
> ```
> go-filecoin chain head
> ```

root@it-System-Product-Name:~/Desktop/ifps/filecoin# go-filecoin show block zDPWYqFD4onJUygV8qNkPB5kh2J9ZQydjqwJW9EiMG2qqYGogJk5
Block Details
Miner:  t2dqagdc3tudvfhvce7cj5ep6scfmvtuyhfjc3vra
Weight: 179303.345
Height: 22316
Nonce:  0
root@it-System-Product-Name:~/Desktop/ifps/filecoin#

**Comment by rosalinekarr** [comment]
Yeah, this seems like a bug. @ZenGround0, would you mind investigating this one?

**Comment by ZenGround0** [comment]
Can someone explain why this appears to be something other than the chain needing to sync for the faucet message to be processed by the local node?

Is there something in the `chain head` output that indicates this?  Is the output head cid the same as the head of the cluster for example?  I don't know how to read the output provided above.

**Comment by travisperson** [comment]
> Height: 22316

The user devnet is at `65593`, if the user has stopped syncing for some reason I think we can look into it further, but at the moment I think they just haven't synced the chain.

**Comment by rosalinekarr** [comment]
oh, my mistake. thanks, @travisperson.

@SCUTVincent, it looks like you just need to sync a bit longer. We know syncing takes an unreasonable amount of time, and it's something we're currently working to improve.

**Comment by rosalinekarr** [comment]
I'm going to close this issue for now. @SCUTVincent, if you still have the issue after chain catches up with the devnet, let me know, and I'll reopen this issue.
