### ISSUE TITLE
go-filecoin daemon should not output PeerID

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/go-filecoin#2599]
### Description

Outputting the user's peerID from `go-filecoin daemon` seems like it's placing a double responsibility on the daemon command and has already lead to some confusion with users. We should remove this log from `go-filecoin daemon` and change the wiki to advise users to get their peerIDs from `go-filecoin id` instead.

### Acceptance criteria

1. `go-filecoin daemon` no longer outputs a peerID
2. The wiki getting started guide is updated to use `go-filecoin id` for fetching the peerID

### Risks + pitfalls

We need to discuss this first and decide if it's actually what we want to do.

### Where to begin

Discussion.

**Comment by RobQuistNL** [comment]
Some "problems" I ran into:

When first starting the daemon, I got a lot of messages like these (coming in every 20 seconds, a batch of messages like these:)
<details>
  <summary>Click to show console output</summary>

```
23:51:56.554  INFO chain.sync: syncing the chain, currently at block height 46981 default_syncer.go:147
23:51:56.933  INFO chain.sync: syncing the chain, currently at block height 44456 default_syncer.go:147
23:51:57.230  INFO chain.sync: syncing the chain, currently at block height 42223 default_syncer.go:147
23:51:57.653  INFO chain.sync: syncing the chain, currently at block height 40206 default_syncer.go:147
23:51:57.972  INFO chain.sync: syncing the chain, currently at block height 38065 default_syncer.go:147
23:51:58.311  INFO chain.sync: syncing the chain, currently at block height 35454 default_syncer.go:147
23:51:58.669  INFO chain.sync: syncing the chain, currently at block height 33236 default_syncer.go:147
23:51:58.907  INFO chain.sync: syncing the chain, currently at block height 30253 default_syncer.go:147
23:51:59.381  INFO chain.sync: syncing the chain, currently at block height 26915 default_syncer.go:147
23:51:59.694  INFO chain.sync: syncing the chain, currently at block height 24823 default_syncer.go:147
23:52:00.247  INFO chain.sync: syncing the chain, currently at block height 22938 default_syncer.go:147
23:52:00.886  INFO chain.sync: syncing the chain, currently at block height 21435 default_syncer.go:147
23:52:01.497  INFO chain.sync: syncing the chain, currently at block height 19507 default_syncer.go:147
```
</details>

`syncing the chain, currently at block height 46981`, in descending order. Its very confusing as its not even syncing the chain (the numbers don't match the reported chain height, the actual syncing seems to happen after), and the numbers going from high numbers to low numbers, on and on, is very confusing.

In between it was cluttered with a lot of messages like these:

<details>
  <summary>Click to show console output</summary>

```
23:52:01.602 WARNI /fil/hello: genesis cid: zDPWYqFCutuHwRZhGXzji9L4eHeoFxxNCxCruGjWje36aAvbK2XV does not match: zDPWYqFCu9VdMN9pUSSttbjJsxd2sTJGZjXv8AGZvquxnsMRFh9e, disconnecting from peer: <peer.ID Qm*eVwka9> hello.go:93
```
</details>

Then there are some other disconnect messages which can be confusing for the user.

Like me, most people will wonder if they set up everything correctly and start to ask questions.

Maybe showing current sync height (like with `go-filecoin chain head`) every once in a while is better. Showing an avarage speed / time indication would be a very nice addition.

Since the daemon output shouldn't really be "read" by users, maybe its nicer to let people set up the daemon in a hidden state. No output (except on hard / unrecoverable errors). Maybe a simple command like `go-filecoin status` to show progress, or `go-filecoin monitor` as a continous stream of status information?

Either way, the output of the daemon seems to be pointed towards experienced users, and its very confusing for people seeing it for the first time - they want to see they setup up their environment correctly, and that the chain is being synced :) Thats all.

**Comment by rosalinekarr** [comment]
@RobQuistNL, this is great feedback. Would you mind opening a new issue for it?

**Comment by anorth** [comment]
@rosalinekarr could you expand on or link to the user confusion? It does seem generally helpful to me for the daemon to report its network addresses (which peer id kindof is) at boot.

**Comment by rosalinekarr** [comment]
@anorth: https://filecoinproject.slack.com/archives/CEGN061C5/p1555503677036100

I feel like the `go-filecoin id` method solves this problem better than having users dig through daemon logs. The daemon logs on boot are fairly short right now, but that may not be the case in the future.

**Comment by anorth** [comment]
I concur that the `id` command should exist, but don't see logging it at boot as causing any problems here. As well as live information (which will be more useful when logs are cleaned up), it will be very for ad-hoc debugging multi-node systems, where logs might be aggregated etc.
