### ISSUE TITLE
Error: couldn't establish connection to miner: dial backoff

### ISSUE THREAD

**Issue by a8159236** [filecoin-project/go-filecoin#2616]
The following error occurs when I store data to other nodes：
Error: couldn't establish connection to miner: 
I tried  'go-filecoin ping <minerPID>', but it didn't work,Display an error： 'Error: dial backoff'.But I can ping other nodes.

**Comment by rosalinekarr** [comment]
@ZenGround0, would you mind answering this one? We might also want to add it to the troubleshooting since a similar question was asked in Slack yesterday.

**Comment by ZenGround0** [comment]
Hey @a8159236 thanks for the question.  This question reflects a common and expected usage issue when using our network.  Because this question is so likely to be asked again and its answer is more relevant to users than developers it is best to answer on our user forum [discuss.filecoin.io](https://discuss.filecoin.io/).  Please head over there and copy paste this question for a quick response.  See you there!
