### ISSUE TITLE
Sector cannot be sealed

### ISSUE THREAD

**Issue by a8159236** [filecoin-project/go-filecoin#2617]
Why is the sector storage time too long?
Hi, I uploaded more than 256MB of files, but I have been in the "staged" state so far, why haven't "posted" for so long?
I store data from one miner to the other, and they follow the following steps:

1, go - filecoin miner create 10 100 - gas - price = 0.001 - gas - limit = 300 - peerid  `go - filecoin id | jq -r 'id'` 

2. Go-filecoin mining start

3, go-filecoin miner set-price --gas price=0.001 --gas limit=1000 0.000000001 2880

4. Go-filecoin client withdraw -storage-deal

I don't know where is wrong, cause I can't seal the stored data, has been "staged" status, already several days, I don't know what advice can you give? But do I have an interrupt in the process of storing data, and then restart the node receiving data, continue to transfer files, because there is an interrupt in the middle? Or in the storage miners in the sealing process can not be dropped, otherwise can not seal the sector?

My machine configuration is as follows:
CPU AMD 200GE
RAM 8G

**Comment by rosalinekarr** [comment]
@frrist, can you handle this one? Also, it looks like someone in the help slack has a similar problem. I'll @ you in the thread.

**Comment by frrist** [comment]
Hi @a8159236 can you please provide us with the following information so that we may better help to debug your problem:

- Go Version: (`$ go version`)
- Filecoin Version (`$ go-filecoin version`)
- System Details: (`$ uname -a`)
- How many nodes you are running on your machine (The issue gives me the impression you are running 2 and trying to make a deal between them)
- Miner Details (node you are storing the file on)
  -  peerID (`$ go-filecoin id`)
  - Miner address (`$ go-filecoin config mining.minerAddress`)
- Client Details (node you are importing the file on)
  - peerID (`$ go-filecoin id`)
  - File size you are importing, and how many files

**Comment by a8159236** [comment]
Hi @frrist  I'm sorry for replying so late. For the previous question, I changed the configuration of the machine for a new test. I used AMD200GE and 8G memory before, but now I change it to AMD200GE and more than 16G memory. It seems that the program is very demanding for hardware. If I change the CPU with higher performance and increase the memory, I wonder whether the performance will be improved.

But I found something new:
The machine does not have me in 'network statistics dashboard' show, even though I have already run: go - filecoin config heartbeat. BeatTarget "/ dns4 / stats - infra. Kittyhawk. WTF/TCP / 8080 / ipfs QmUWmZnpZb6xFryNDeNU7KcJ1Af5oHy7fB9npU67sseEjR"

Finally, I would like to ask if there is any system requirement to install Filecoin. Besides Ubuntu, is it ok to use Centos? Or is it better to use Ubuntu?

**Comment by frrist** [comment]
Any linux distros should be fine. What version of go-filecoin are you running? Also be sure to follow the [Getting Started Instruction](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started).

Can you provide me with the number of files you are attempting to store as well as their sizes?

**Comment by a8159236** [comment]
@frrist With the latest installation package (filecoin-0.1.4-linux.tar.gz), I uploaded two video files, each about 200MB.

**Comment by frrist** [comment]
I had a conversation with @laser and he create this outline:

# Why is my deal stuck in the `Staged` state?

## Was my piece too big?

If a storage client C proposes a deal D with a miner M and that D references a piece P whose size is less than or equal to the size of M's staged sector, P will be transferred from C to M and M will write P to its staged sector. The state of D will be `Staged` at this point.

If the state does not equal `Staged` immediately after C proposes a deal with M and transfers the bytes, then P isn't "waiting to be sealed." This can happen if the size of P is larger than size of the sector. In the devnet/user cluster, that size I speak of is `266338304` bytes.

## At which point will the state of D move from `Staged` to `Posted`?

If the state of D is `Staged`, then the miner has accepted P and written it to a staged sector S. **If M isn't using auto-sealing**, P will sit in S until M receives a new deal D2 proposal whose piece P2 is large enough such that size(P) + size(P2) >= free-space(S). When this happens, M will start sealing S. When sealing completes, the state of D will become `Posted`.

## Why hasn't _my_ deal transitioned to `Posted`?

Our users in the devnet/user cluster can make deals with any miner - not just the ones which PL set up - and it's entirely possible that the miner that they made the deal with is:

1) not using auto-sealing and
2) still waiting for new deals to come in such that it fills up the staged sector sufficient to seal it

## How can I make sure that my piece is sealed?

To ensure that your piece is sealed into a miner's staged sector, ensure that the size of your piece equals the amount of user bytes which can be written to a staged sector. In the devnet/user cluster, this number is `266338304`.

To create such a piece and store its CID in `PIECE_1_CID`, a storage client can run the following commands:

```
PIECE_1_PATH=$(mktemp)
dd if=/dev/urandom of="${PIECE_1_PATH}" bs=$((1024*1024)) count=254
PIECE_1_CID=$(./go-filecoin client import < ${PIECE_1_PATH})
```

-----------------

@a8159236 to answer your original question:
>I uploaded more than 256MB of files, but I have been in the "staged" state so far, why haven't "posted" for so long?

Based on the information you have provided, this is likely because the miner(s) the deal was made with does not have auto-sealing enabled. You may configure it to auto-deal using the `auto-seal-interval-seconds` flag defined [here](https://github.com/filecoin-project/go-filecoin/blob/966fe75919755074c7c2724f2c9634c2b61d4212/commands/init.go#L37). I believe there is enough information here to address your issue. If this problem persists after following the above outline feel free to re-open the issue.
