### ISSUE TITLE
go-filecoin message wait stuck

### ISSUE THREAD

**Issue by jcchua** [filecoin-project/go-filecoin#2618]
I am stuck at go-filecoin message wait for many hours 
Should I drop it or continue to wait?
zDPWYqFD7DyqwVcQhZKCXkqbT8XCGccRygjqbbPd4DvPLLLmRwH8

**Comment by mkky-lisheng** [comment]
Can you elaborate on the description? Or give me a hint.

**Comment by jcchua** [comment]
I follow the instruction at https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started  till "Get FIL from the Filecoin faucet"  

I am stuck at
3. The faucet will provide you with a message CID. The message should be processed in about 30 seconds.  You can run the following command to wait for confirmation:

go-filecoin message wait ${MESSAGE_CID}

This is the  CID: zDPWYqFD7DyqwVcQhZKCXkqbT8XCGccRygjqbbPd4DvPLLLmRwH8

The Block Details
Miner:  t2a7yqktnfxhacl5756gsoijppdznz2bk5uv5rcwy
Weight: 212809.975
Height: 32210
Nonce:  0

**Comment by rosalinekarr** [comment]
@jcchua, this is a [known issue](https://github.com/filecoin-project/go-filecoin/issues/2050). Message wait does work, it just takes a very, very long time due to chain syncing at the moment. There's already some work in progress to help speed it up. In the mean time, I'm afraid the best we can suggest is just leaving your daemon running for a few days.
