### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/go-filecoin#2631]
Describe:
The filecoin daemon will crash while facing non-stop deal-proposals from a client.

Log:
fatal error: concurrent map iteration and map write

goroutine 17856 [running]:
runtime.throw(0x1487c85, 0x26)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0c2793c68 sp=0xc0c2793c38 pc=0x4e3e62
runtime.mapiternext(0xc0c2793d48)
	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc0c2793cf0 sp=0xc0c2793c68 pc=0x4c5657
github.com/filecoin-project/go-filecoin/core.(*MessagePool).timeoutMessages(0xc01bfcc210, 0x16d9ce0, 0xc052c84800, 0x7f0505288f30, 0xc0001a5180, 0xc06e913590, 0x80, 0x100)
	/root/go/src/github.com/filecoin-project/go-filecoin/core/message_pool.go:185 +0x203 fp=0xc0c2793db8 sp=0xc0c2793cf0 pc=0xbbc063

Suggest:
core/message_pool.go 185 line
// remove all messages added before minimumHeight
pool.lk.Lock() // lock
defer pool.lk.Unlock()
for cid, msg := range pool.pending {
	if msg.addedAt < minimumHeight {
		pool.Remove(cid)
	}
}

**Comment by ZenGround0** [comment]
Hey @diwufeiwen, first thank you for filing a bug report!

However, because you did not include the `go-filecoin version` information this bug report is hard to do anything with.  In the future please fill out the complete bug report template to make bugs actionable.  

Without more information the best explanation is that this is the bug initially suggested to be fixed [here](https://github.com/filecoin-project/go-filecoin/pull/2486) and actually fixed [here](https://github.com/filecoin-project/go-filecoin/pull/2522/files).  Note that the fix will only make its way to the user devnet after our next release in 2-3 weeks.

If I am mistaken and this issue is showing up on most recent master after the above fix was merged please reopen with the complete bug report template filled out.
