### ISSUE TITLE
[bug]concurrent map iteration and map write

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/go-filecoin#2645]
Describe:
The filecoin daemon will crash while facing non-stop deal-proposals from a client.

Version:test-devnet-0.1.4

Log:
fatal error: concurrent map iteration and map write

goroutine 17856 [running]:
runtime.throw(0x1487c85, 0x26)
/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0c2793c68 sp=0xc0c2793c38 pc=0x4e3e62
runtime.mapiternext(0xc0c2793d48)
/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc0c2793cf0 sp=0xc0c2793c68 pc=0x4c5657
github.com/filecoin-project/go-filecoin/core.(*MessagePool).timeoutMessages(0xc01bfcc210, 0x16d9ce0, 0xc052c84800, 0x7f0505288f30, 0xc0001a5180, 0xc06e913590, 0x80, 0x100)
/root/go/src/github.com/filecoin-project/go-filecoin/core/message_pool.go:185 +0x203 fp=0xc0c2793db8 sp=0xc0c2793cf0 pc=0xbbc063

Suggest:
core/message_pool.go 185 line
// remove all messages added before minimumHeight
pool.lk.Lock() // lock
defer pool.lk.Unlock()
for cid, msg := range pool.pending {
if msg.addedAt < minimumHeight {
pool.Remove(cid)
}
}

**Comment by ZenGround0** [comment]
@diwufeiwen thank you for including "Version:test-devnet-0.1.4".
This bug has been fixed on master but it is expected to exist when using this binary because the fix was merged after 0.1.4 was built.  Please wait for the next release at which point this problem will be gone.

If you want to test that this bug is actually fixed on master please build master, connect to the nightly devnet and run this new node through the same series of tests.
