### ISSUE TITLE
TestPaymentChannelLs/Works_with_specified_payer is flaky

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#2661]
### Description
Here is the log output from travis:
```
    --- FAIL: TestPaymentChannelLs/Works_with_specified_payer (3.81s)
        require.go:794: 
            	Error Trace:	payment_channel_daemon_test.go:583
            	            				payment_channel_daemon_test.go:109
            	Error:      	Received unexpected error:
            	            	filecoin command: [go-filecoin paych create t1o4t7xzfykkddl5cyn4rxx2h2iwd4qploy3scblq 1000 20 --from t1tqc4pjlf4q6womlxohc3exl2na23yh7gcbmmskq --gas-price 1 --gas-limit 300 --enc=json], exited with non-zero exitcode: 1
            	Test:       	TestPaymentChannelLs/Works_with_specified_payer
```

This sometimes fails and sometimes passes locally

**Comment by travisperson** [comment]
Waiting on https://github.com/filecoin-project/go-filecoin/pull/2627

**Comment by travisperson** [comment]
Repro'd after #2627 landed: https://circleci.com/gh/filecoin-project/go-filecoin/14849#tests/containers/1

**Comment by travisperson** [comment]
```
log_writer.go:44: ---- command     go-filecoin paych create t1oklanfdcktpnpt5tligkwx6n24ac7xcnyxoky6q 1000 20 --from t1ehw5mp5ycsqu7z6ywluylntilwkwqifydray25q --gas-price 1 --gas-limit 300 --enc=json
log_writer.go:44: ---- exit-code   1
log_writer.go:44: ---- error       nil
log_writer.go:44: ---- stdout
log_writer.go:44: ---- stderr
log_writer.go:44: Error: no actor at address t1ehw5mp5ycsqu7z6ywluylntilwkwqifydray25q: actor not found
log_writer.go:44: <<<< end-dump
```

Originally I thought this might be an issue around message not showing up in the mpool before we mined a block. However, in that failure I would actually expect to see a timeout I believe because the `message wait` would hang forever.

In this case, we see that the actor is not found which means that the node we are running the `paych create` on does not have a block with funds sent to the address. We do send funds to it.

This looks to be due to the fact that we only are waiting on the message on the node which produced it (and in this case mined it).

https://github.com/filecoin-project/go-filecoin/blob/66089103c636ac52bf0ef3bdaca18bafdc210b6b/tools/fast/series/send_filecoin_from_default.go#L20-L27

This should be an easy fix. `SendFilecoinFromDefault` should probably not longer wait, but instead return a `mcid`, in `SendFilecoinDefaults` we will wait on this message on the targeted node.

**Comment by anorth** [comment]
Ancient history
