### ISSUE TITLE
Replace strict devnet version checking with protocol-compatibility check

### ISSUE THREAD

**Issue by ognots** [filecoin-project/go-filecoin#2685]
### Description
Introduced in 0.1.4, go-filecoin checks that it is running the same version (at the same commit) while connecting to a devnet. This was intended as interim until protocol upgrades are implemented.

Relax check to allow upgrading go-filecoin in devnets without resetting chain, while still ensuring compatibility.

### Acceptance criteria
- [ ]  go-filecoin binary version can be upgraded while retaining local repo state
- [ ] devnet genesis and bootstrap nodes can be updated while retaining local state and chain height
- [ ] two or more compatible binary versions can run on the same network

### Risks + pitfalls
Added complexity tracking version compatibility

### Where to begin
Consider checking for a minimum version ie. `>= 0.1.4`

**Comment by anorth** [comment]
Added to the protocol upgrade epic. Any change we make here should be in concert with that work.

**Comment by acruikshank** [comment]
Protocol version is currently an unsigned int. I haven't come across a compelling reason to use semver since we don't need to distinguish between compatible changes and the cryptographic nature means that even the smallest change completely breaks compatibility. If we need this in the future, the current version could become the major version.
