### ISSUE TITLE
In types/tipset.go those func (ts TipSet) maybe should be func (ts *TipSet)?

### ISSUE THREAD

**Issue by jscode017** [filecoin-project/go-filecoin#2703]
### Description
I am curious that why why in types/tipset.go the functions are func (ts TipSet) instead of func (ts *TipSet)?

**Comment by frrist** [comment]
Hi @jscode017, methods on `types/tipset.go` are defined as value receivers primarily due to thread safety, and with the exception of `AddBlock`, not needing to modify the receiver value.

Here are a couple links for more information on choosing value vs pointer receivers when writing go:
- https://flaviocopes.com/golang-methods-receivers/
- https://tour.golang.org/methods/8
