### ISSUE TITLE
User devnet 0.2.1 extremely slow progress

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2755]
A few hours after the genesis of the user devnet `0.2.1`, the chain appeared to halt around block 380ish. Now (about 8 hours after genesis) the [network stats](https://stats.kittyhawk.wtf/) shows a best block height of 656. The expectation of a healthy network would be around 960. This issue is to track our investigation and resolution.

Many nodes reported lots of nonce too high errors (#2748). Some nodes reported panics in libp2p metrics(#2753). It's not clear if either are directly responsible for the slow progress.

Individual nodes appear to be struggling to receive the chain - a node that I am running is around block 450, progressing very slowly. My log contains lots of peer connection failures, but I am not sure this is typical.

```13:17:05.197 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*iT2kgH>: stream reset hello.go:179
13:17:05.274 WARNI net/identi: error reading identify message:  stream reset id.go:146
13:17:13.773 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*kiMFvh>: write tcp4 192.168.0.87:6000->125.64.108.41:6000: use of closed network connection hello.go:179
13:17:13.908 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*U2ih2N>: session shutdown hello.go:179
13:17:13.909 WARNI net/identi: error reading identify message:  stream reset id.go:146```

**Comment by anorth** [comment]
One hypothesis is that nodes from the prior version of the user devnet are interfering with the progress of this one. Maybe the network is flooded with messages and blocks from the old network, squeezing out the new one?

The DHTs are shared until issues like #2509 are resolved. We have experienced turbulence like this at each new release. One possible quick fix right now would be to change the DHT protocol version to segregate the network.

Nodes currently check for compatibility in the hello protocol, but I don't believe that other protocols (like message and block pubsub) are gated behind the hello protocol success. It's not immediately clear to me that segregating the DHTs would also effectively segregate these channels.

**Comment by anorth** [comment]
Another hypothesis is that a significant amount of the storage power went offline (possibly due to #2753), since these devnets are not secured by a large, distributed set of miners. If the storage power is offline, maybe it keeps winning elections and failing to produce blocks, so the network slows? Maybe @whyrusleeping can answer this.

At one point I observed only ~20% of power reporting to the dashboard.
<img width="1197" alt="Screenshot 2019-05-09 11 58 03" src="https://user-images.githubusercontent.com/445306/57425463-95f71100-725e-11e9-94b8-00accb226f1d.png">

Now there's more like 60% and progress seems better. 
![Screenshot 2019-05-09 13 30 50](https://user-images.githubusercontent.com/445306/57425507-bde67480-725e-11e9-9b26-798e07465cf4.png)

Reporting power to the dashboard is opt-in, so this will always under-report. I'm not sure whether the reported storage power is a symptom or cause.

**Comment by anorth** [comment]
I realise I have been misreporting my node's chain height. 

Right now `go-filecoin chain head` shows `zDPWYqFCxUJL4uyGXno6FoMo7GcVKmHnLufwRfQGjV7N6iQR4tS1` which is block 696 and the current head according to the block explorer.

`go-filecoin chain ls | wc -l` shows 468, which I guess is excluding null blocks. My node is up to date with the chain despite all the log messages.

Is this the best way of reporting chain sync state: `./go-filecoin show block $(./go-filecoin chain head)`? Or am I missing something?

**Comment by anorth** [comment]
A few hours later, and the chain is making faster progress than expected! Block times seem to have dropped toward 15 seconds as of block 1961.

**Comment by whyrusleeping** [comment]
Yeah, we probably need to implement slashing inactive miners out. If only 20% of the miners are online, then the chain will go 5x slower.

**Comment by acruikshank** [comment]
These no-coordination hard-fork releases have gotten a lot more disruptive. That may be part of the problem.

I would expect %20 storage power online to mean we have a lot more null blocks, but no change in block time. 

The only exception I know of is that a miner with storage power that just joins the network after a long chain of null blocks will start mining at a lower block height. This would have the effect of lowering the block height relative to clock time. But it's hard to imagine how this could happen often enough to have much effect on the average block time.

**Comment by ognots** [comment]
@acruikshank the graphs would suggest block time was effected yesterday.

![time-since-last-block](https://user-images.githubusercontent.com/47555507/57466376-7eb02780-724e-11e9-842d-6ecdccb0b7a6.png)

**Comment by acruikshank** [comment]
@ognots The graph seems to suggest that there were 2 hours where no blocks were mined at all, and some time surrounding where block times were closer to expectation. So I see this as two puzzles:

1. What happened from 19:30 to 21:30 such that no one was able to mine a block? I could believe that no user miner with the correct code happened to be online at that time, but the bootstrap miners should have still been available.
2. What accounts for block time irregularities outside that big 2 hour blackout?

**Comment by travisperson** [comment]
It looks like the large delay in blocks reported by the nodes we are monitoring was due to a block from the previous run of the user devnet being published to the nodes.

All of our nodes recieved the block mentioned below, but I only looked into the timeline of a single node, as all others should of followed the same steps.


- [`2019-05-08T23:14:02.978Z`]: Received `Block cid=[zDPWYqFCywUiaoZEQqdjT2MEz74934zx9LUKf3u8k8WMJ5ZxrnFy]` from some peer of the previous user devnet.
  - The block has a height of `117098`

When we receive a block, we then try to collect from it, to what we have in our store. Because this block has no ancestory in our chain store, we end up spending a large amount of time requesting these blocks from the network. Suprisingly a node was able to provide these messages.

- [`2019-05-08T23:14:02.979Z`]: `CollectChain next link: { zDPWYqFCywUiaoZEQqdjT2MEz74934zx9LUKf3u8k8WMJ5ZxrnFy }`
  - Height: `117098`
- [`2019-05-08T23:14:11.652Z`]: `CollectChain next link: { zDPWYqFCrbygecXhS4pE2sa53VyrbuNXKpiVfwqso62PYQdUT8j3 }`
  - Height: `117096`
- [`2019-05-08T23:14:20.183Z`]: `CollectChain next link: { zDPWYqFD3vrCqGnX6C7gKw7qeZo7GSmHskwRPDtCJWcXkXqgeqkG }`
  - Height: `117092`
- [`2019-05-08T23:14:23.631Z`]: `CollectChain next link: { zDPWYqFD8CYGJK2npivPXhwwrkM6T4xxr8Gi6wf8nPJk4zFKisVA }`
  - Height: `117049`
- [`2019-05-08T23:14:27.946Z`]: `CollectChain next link: { zDPWYqFD1NeRmtnkzPvTa3dKGFhMLqTCLHNb66bEYLsNrVZKExYw }`
  - Height: `117044`


This goes on for about two hours before we receive a new block from pubsub at `2019-05-09T01:10:10.768Z`. However, this is still an old chain block with a height of `117914`.

At `2019-05-09T01:15:26.047Z` we receive a block with height `399`.

This goes on for hours as far as I can tell.

**Comment by travisperson** [comment]
So this halting issue is because we can only handle one block pubsub message at a time.

https://github.com/filecoin-project/go-filecoin/blob/fcf56acdc98a2ea4fc4d0b62878a9302f51af869/node/node.go#L1030-L1044

The call to `f` needs to return before we call `s.Next()`. This is `processBlock` for the incoming tipsets.

https://github.com/filecoin-project/go-filecoin/blob/fcf56acdc98a2ea4fc4d0b62878a9302f51af869/node/block.go#L41-L65

`HandleNewTipset` needs to return before `processBlock` returns, so it makes sense that we won't receive a block during this time.

So when a node publishes a _very_ long chain, we always try to download it. This means that a user could generate a massive chain, spam it out everywhere and get a bunch of nodes to start down the path of fetching the blocks. As long as long as collectChain doesn't time out (30 seconds). A node can basically lock up anyone they want to with a targeted message publish, and sticking within the 30 second timeout.

https://github.com/filecoin-project/go-filecoin/blob/522cefefb2b6db8537d8742a4b86801b5ed4e939/chain/default_syncer.go#L24
https://github.com/filecoin-project/go-filecoin/blob/522cefefb2b6db8537d8742a4b86801b5ed4e939/chain/default_syncer.go#L90-L102

**Comment by whyrusleeping** [comment]
We should use a topic validator for blocks and messages. They allow limited configurable concurrency, and if the validator returns a failure, then the message does not get propagated. The question becomes how much validation do we want to do here? The best for the network is likely to do all the validation here, but that slows down propagation time, so maybe we could do some 'fast checks' there, return a successful validation, then do the slow checks. The option for adding the topic validator to the pubsub engine is here: https://github.com/libp2p/go-libp2p-pubsub/blob/master/pubsub.go#L930

Additionally, we should not sync to a chain that is more than 'finality' blocks away from our current head (assuming we are not desynced from the network). We know when the genesis block was created, and if we receive a block that is significantly farther in the future than the current time (assuming 30 seconds per block since genesis) then we should drop it. (This behavior should not apply during bootstrap sync, only caught up sync)

**Comment by mishmosh** [comment]
@anorth will summarize takeaways & recommended actions

**Comment by anorth** [comment]
I've extracted the actions into #2782 and #2783. Closing this in favour of those.
