### ISSUE TITLE
Remove "Blocked" ZenHub pipeline

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2787]
### Description
We have a ZenHub pipeline named Blocked, with a few issues in it. I don't find this pipeline useful for prioritisation and sequencing stories and propose we remove it. 
- Blocked is mutually exclusive with Backlog, Ready etc so the fact that we can't proceed right now obscures whether or not we intend to. 
- Being in the Blocked pipeline doesn't identify what is blocking an issue, which we could better indicate another way.
- We have a lot of pipelines, and Blocked doesn't appear "left of the fold" on most common monitor configurations, leading to the issues being ignored

I propose we replace it with (as appropriate):
- Explicitly linking dependee issues
- Writing words describing the external blocking item
- A `blocked` tag

Blocked issues might then typically go in the backlog, for consideration among other Backlog issues. Where we expect a blockage to be resolved shortly, a blocked issue could remain Ready.

We can experiment with this, and revert in a month or so if we don't like it.

### Acceptance criteria
- No Blocked pipeline
- Existing blocked issues are linked to dependees, or tagged and the reason noted in
 a comment
 - An agreed date upon which committers will review this change

**Comment by mishmosh** [comment]
The main difference between Backlog & Blocked is that we are actively awaiting progress and nudging if needed. 

The "Blocked" designation has been very useful to me & team in the past, eg libp2p relay work and I would like to keep it.

When moving to blocked, we should be noting what is blocking -- eg https://github.com/filecoin-project/go-filecoin/issues/1583

**Comment by rosalinekarr** [comment]
Maybe the "Blocked" should have some indication that it refers to blockers outside the context of go-filecoin? Alternatively, we could create some labels that explain what the blocker is more specifically, e.g. `pending-spec`, `blocked-by-proofs-work`, etc.

**Comment by frrist** [comment]
I would be in favor of removing the blocked column and using the zenhub dependency "Blocked by" or "Blocking" instead.
![blocked](https://user-images.githubusercontent.com/6546409/58112565-a2f1f980-7ba8-11e9-8a1d-57e092d0505f.png)
This will force us to created an issue when we get blocked, currently this is not explicitly enforced via the blocked column.

Since Zenhub encompases almost all repos in the "filecoin-project" (e.g. spec, proofs, infra), we can link to them even if they are outside of "go-filecoin" repo.
For work that is blocked by an issue not under the "filecoin-project" (libp2p, ipfs, ipfs) we can create an issue in go-filecoin stating that we should upgrade to a later version and link to the issue in the external repo.

-----------------------------------

It is also worth noting that we have a label called "PROTOCOL BREAKING" that is used to indicate a sync is needed between the go-filecoin code and the spec.
