### ISSUE TITLE
reduce load time in debug 

### ISSUE THREAD

**Issue by urugang** [filecoin-project/go-filecoin#2847]
here is my go-filecoin daemon start log.     
it (DefaultStore.Load) waste too much time (16 min).  now i want to debug propose-storage-deal, I need wait for 16 minutes, it is not tolerable specially when there are so much issue to be solved. 
I think we can save result after close, and load directly after start. 
```
5月 29 09:25:53 go-filecoin[8059]: 09:25:53.568  INFO     badger: Replaying file id: 0 at offset: 52578
5月 29 09:25:53 go-filecoin[8059]:  logger.go:46
5月 29 09:25:53 go-filecoin[8059]: 09:25:53.569  INFO     badger: Replay took: 16.984µs
5月 29 09:25:53 go-filecoin[8059]:  logger.go:46
5月 29 09:25:53 go-filecoin[8059]: My peer ID is QmNTKL3FbAxu9D3aZza1mUdVt2SRazXLX472d5RDZbHrYB
5月 29 09:25:53 go-filecoin[8059]: Swarm listening on: /ip4/127.0.0.1/tcp/6000
5月 29 09:25:53 go-filecoin[8059]: Swarm listening on: /ip4/192.168.31.118/tcp/6000
5月 29 09:25:53 go-filecoin[8059]: Swarm listening on: /ip4/192.168.192.128/tcp/6000
5月 29 09:25:53 go-filecoin[8059]: 09:25:53.571  INFO chain.stor: start loading chain at tipset: { zDPWYqFCvCYVeiWFZFUwgdatGFffaYqo8BHv4boWp8aXhASzcvT6 }, height: 159528 default_store.go:121
5月 29 09:25:53 go-filecoin[8059]: 09:25:53.836  INFO chain.stor: load tipset: { zDPWYqFD1zAxoT17dfNCnFbxp5hU93WSZBeGvQ3YLDFjEAQaYdMX }, height: 159520 default_store.go:136


5月 29 09:40:47 go-filecoin[8059]: 09:40:47.267  INFO chain.stor: load tipset: { zDPWYqFCySnH9Efy2bHnERatKacH2U6NqXqJ7JSMfPovbHVxPceT }, height: 79760 default_store.go:136
5月 29 09:49:21 go-filecoin[8059]: 09:49:21.071  INFO chain.stor: load tipset: { zDPWYqFCxc13Bh1tGJapv4dRUiHB65gDGWpMUxaq3XcMebWA3CZA }, height: 15952 default_store.go:136
5月 29 09:56:04 go-filecoin[8059]: 09:56:04.453  INFO chain.stor: load tipset: { zDPWYqFD6sE4HBMtXghMsEsm3SwJ4u8bmt3f5VJ4vzVc1j4LgL62 }, height: 0 default_store.go:136
5月 29 09:56:04 go-filecoin[8059]: 09:56:04.511  INFO chain.stor: finished loading 159528 tipsets from { zDPWYqFCvCYVeiWFZFUwgdatGFffaYqo8BHv4boWp8aXhASzcvT6 } default_store.go:162
```

**Comment by frrist** [comment]
Thanks for the issue report. Could you include details below so we can investigate?

Please reopen this issue once more info is available, and we'll be happy to take another look.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Run this command '...'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots or Console Output**
The output of `go-filecoin inspect all` and if applicable, add logging output or screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [if applicable, e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
