### ISSUE TITLE
Define standard default output format

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/go-filecoin#287]
### Description

From discussion in #274, @phritz wrote: 'Could you please propose a standard default output format in the contributing guide, maybe informed by a short convo with why? I think we want something that is not json but is pretty printy.'

I'm creating this issue as  TODO for myself so I don't lose track when #274 merges.

I discussed this with @whyrusleeping. Tentative conclusions:

+ This has to be excellent and work correctly eventually, but is not yet top priority.
+ Getting this right is tricky.
+ It would be best to follow IPFS if possible.

@laser's comment from #274 may therefore be relevant:

> It is my belief that we want to do things like IPFS does as a general rule. Some go-ipfs commands have a notion of "format", which allows the caller to provide a string containing some tokens used to create command output. See [here](https://github.com/ipfs/go-ipfs/blob/11ce0445cb24b6b99613223fc6d8128c6648a4df/core/commands/files.go#L103) and [here](https://github.com/ipfs/go-ipfs/blob/11ce0445cb24b6b99613223fc6d8128c6648a4df/core/commands/files.go#L173) for an example.

### Proposal

+ For now, just don't implement text-encoders at all. Better to get this right than insert a stopgap. There's always JSON available from the CLI.
+ For each missing text encoder, spawn a new issue to track the deficit.
+ When implementing the first of these, just focus on defining a standard (non-customizable) format with emphasis on human-readability.
+ Prefer defining standard textual outputs for each necessary type independently and composing these representations -- as opposed to crafting entirely novel representations for each composite data-type or result.
+ Do include appropriate human-readable scaffolding as necessary for readability, on a case-by-case basis. (@whyrusleeping is this right?)
+ Define such textual renderers such that they can be reused between commands' text encoders.
+ Once this pattern has been established, when completing the issue associated with a command whose output warrants it, implement a text-substitution based approach (like shown in the links above) to allow for user-supplied formatting.

It follows that we should defer working on the most complicated renderers until some groundwork has been covered in the simpler ones.

While this description completely fails to fully define a standard default output format, it does provide a default strategy (do nothing), and an incremental approach to designing a correct and general solution.

For this to work, we should to some extent anticipate and allow for 'design in review' when the relevant PRs come up. This is because getting the details right is tricky and can probably only be discussed well in the presence of concrete examples.

**Comment by anorth** [comment]
I was about to file another issue for something like this, let me comment here instead.

I think this is of higher value now that we have some users. As they get used to our system and we write documentation and many other people start using and building things on top of filecoin, it will become harder to change these outputs and we'll pay large costs for change.

Despite this issue's proposal, I have observed custom text formatters and felt obligated to [write my own](https://github.com/filecoin-project/go-filecoin/blob/6c6f511bf60cad8adc76f2e09c49add10bf97310/commands/mpool.go#L82) for new commands, but with no clear guidance. They are a pain since there's no support code (c.f. JSON). Without support code, the outputs will rot as different developers work on the code. That is, we're paying the cost anyway without much benefit.

I personally think that pretty-printed JSON is superior to most developer-invented output formats. For a great example, consider the AWS CLI tools, which are JSON all the way. JSON achieves good usability and great developer efficiency. I'm sure I don't need to harp on about programabilitya and `jq`. We have to maintain JSON outputs anyway. I think it's a good tradeoff. If JSON is too ugly and/or space-inefficient, consider YAML instead. I think we'll really struggle to consistently beat it for usability. I note that this is a UI for developer and sysadmin users, it will never be for non-technical people.

Note that even our JSON output is inconsistent. `mpool ls` prints multiple JSON outputs, one per line, while others produce a valid single JSON object. While `jq` can deal with this, many other tools will barf.

Finally, I note that our JSON outputs leak implementation details of go-filecoin internals. The problem is that changing the internal organisation will change output formats, and we'll break the explicitly programmable output or need to do extra work to preserve output that isn't great anyway. At some point, possibly soon, we should define structures for command output that are distinct from the structures used internally, even though in many cases they will align closely.

cc @phritz

**Comment by whyrusleeping** [comment]
> Note that even our JSON output is inconsistent.

via the API, this is accompanied by different content type headers, ndjson vs json.

> Finally, I note that our JSON outputs leak implementation details of go-filecoin internals.

They really shouldnt be, The entire point of having a 'Type' field explicitly set in the commands was to avoid this happening. The role of the command is to munge whatever it gets from the system into the consistent format we are presenting to the user.

> At some point, possibly soon, we should define structures for command output that are distinct from the structures used internally, even though in many cases they will align closely.

Yep. agreed

In general, I think that JSON is useful for some commands, especially lower level commands. But for many common commands people will be using, (wallet commands, id, swarm connect type things, sending messages) it will make the experience of using filecoin significantly nicer. More 'normal' people will use go-filecoin on the command line than you'd expect.

**Comment by anorth** [comment]
Relevant discussion for #3098, which may make this obsolete in many ways. I think this issue is specifically about what the CLI presents to human users, though, so still an independent item.
