### ISSUE TITLE
[bug]All nodes are offline, whether Filecoin devnet has crashed ？

### ISSUE THREAD

**Issue by zhengboowen** [filecoin-project/go-filecoin#2903]
All nodes are offline, whether Filecoin devnet has crashed ？

The website of Filecoin devnet shows that there are many nodes’ block height reached more than 1.5 million. I want to know if this is normal.

<img width="1001" alt="All nodes are offline, whether Filecoin devnet has crashed" src="https://user-images.githubusercontent.com/51158073/59104129-4a21af80-8963-11e9-9aaa-e4a6a24715a4.png">

**Comment by rosalinekarr** [comment]
@zhengboowen, we're investigating this right now.

@mslipper @frrist, can you update here when we have more answers?

**Comment by frrist** [comment]
Hey @zhengboowen, this behaviour is not normal and will be addressed in the next major release (0.3.*).

This was more than likely caused by a node encountering a chain that was greater than finality limit ahead, the fix for this [exists here](https://github.com/filecoin-project/go-filecoin/pull/2799).
