### ISSUE TITLE
[bug] TestDealsRedeem fails due to rounding error non-deterministically 

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2960]
**Describe the bug**
`TestDealsRedeem` is failing in CI due to what appears to be a rounding error.

**To Reproduce**
Run the `TestDealsRedeem` test. It is a non-deterministic failure, meaning you nay need to run this more than once.

**Expected behavior**
The test passes everytime.

**Screenshots**
```
Failed
deals_daemon_test.go:88: 
Error Trace:	deals_daemon_test.go:88
Error:      	Not equal: 
            	expected: "11.9"
            	actual  : "11.8999999999999998"
            	
            	Diff:
            	--- Expected
            	+++ Actual
            	@@ -1 +1 @@
            	-11.9
            	+11.8999999999999998
Test:       	TestDealsRedeem
log_writer.go:44: >>>> start-dump
log_writer.go:44: ---- command     go-filecoin client query-storage-deal zDPWYqFCvC1dkmvRfGkT7cikBPPyvgWu4yXjD98qt864Y8eDpQ8a --enc=json
log_writer.go:44: ---- exit-code   0
log_writer.go:44: ---- error       nil
log_writer.go:44: ---- stdout
log_writer.go:44: {"State":5,"Message":"","ProposalCid":{"/":"zDPWYqFCvC1dkmvRfGkT7cikBPPyvgWu4yXjD98qt864Y8eDpQ8a"},"ProofInfo":{"SectorID":1,"CommitmentMessage":{"/":"zDPWYqFD6txFXsghC6uHvTj6N1UcGVBy8dhMZhT2FfkLBJfELQDE"},"PieceInclusionProof":"EiDAatZGvn+eyPm7KNRJwqivm0N7cEiXXa3b7cVidIjOj7LnXHSl3rilpTB0y3iPbjl8G8URqk4deoNhVfyyDw=="},"Signature":"c2lnbmF0dXJycmVlZQ=="}
log_writer.go:44: ---- stderr
log_writer.go:44: <<<< end-dump
log_writer.go:44: >>>> start-dump
log_writer.go:44: ---- command     go-filecoin wallet balance t1kfxxwlc7jr2i4qrnuy53ecbzaqwrshcslcaatey --enc=json
log_writer.go:44: ---- exit-code   0
log_writer.go:44: ---- error       nil
log_writer.go:44: ---- stdout
log_writer.go:44: "9810.8999999999999998"
log_writer.go:44: ---- stderr
log_writer.go:44: <<<< end-dump
```
Here is a failure in CI: https://circleci.com/gh/filecoin-project/go-filecoin/20608#tests/containers/1

**Comment by anorth** [comment]
Thanks for filing this. There are two very important things for us to understand in order to close this issue.
1. why is there a rounding problem
1. why is it nondeterministic

Both of these are critical for confidence in a financial system.

**Comment by travisperson** [comment]
This is probably because the miner sometimes will mine a block with messages and will be rewarded the gas to process the message.

https://github.com/filecoin-project/go-filecoin/blob/8de8451d1ac6be4c3b1f850460269a0294bb3d3f/node/node.go#L829-L848

The `commitSector` messages have a gas price of 1 AttoFIL.

**Comment by travisperson** [comment]
I think gas was originally suggested, but dismissed because of the incredibly small value. The above popped out at me when I was looking into the mining code when filing another issue. I'm not sure where the factor of 2 comes from through as the default gas charge I believe is 100. So for a gas price of 1<sup>-18</sup> we should see a difference of 1<sup>-16</sup>, but we are seeing 2<sup>-16</sup>.
