### ISSUE TITLE
Should the SystemClock go on the Porcelain API?

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2961]
### Description
In https://github.com/filecoin-project/go-filecoin/pull/2899 a `types Clock interface`, `SystemClock` and `FakeSystemClock` were added. The `Clock` can be used by services to get the current time without importing the `time` package. This makes testing easier as we can fake the `Clock` interface.

The `DefaultMinerWorker` and `DefaultBlockValidator` both need access to the clock (miner uses it to timestamp blocks, and validator uses it to validate timestamps). Should this clock be passed to the constructors for these types, or should it be added to the Porcelain API (which they would then accepts)? 

### Acceptance criteria
- A decision is reached on whether or not to put the clock interface in method constructor or on the Porcelain API.

**Comment by anorth** [comment]
My first instinct is that it should not be part of porcelain, but be directly injected at construction of those components that need it. Unless *everything* is part of porcelain, this is one of the common things that doesn't need to be.

However, I could be convinced otherwise by seeing that standard DI ends up being a real mess.

**Comment by frrist** [comment]
Closing as the clock has found a good home, issue no longer relevant.
