### ISSUE TITLE
Integration tests for payment voucher redemption

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#2965]
### Description
The TestDealsRedeem daemon test, apart from being flaky (#2960) takes many minutes because it waits for a sector to be sealed. This is not acceptable duration for an integration test that developers are expected to run with any frequency.

Voucher redemption after a successful deal must be tested without waiting for real sector sealing. This probably means an in-memory integration test.

It's probably still appropriate to leave a stable version of the existing test as a functional test, to be run occasionally on CI and to validate real networks.

### Acceptance criteria
- Payment voucher redemption is integration tested but only takes a few seconds

### Risks + pitfalls
- We don't have good patterns for this yet, this is an opportunity to define them.

### Where to begin
See also #2822, #2194.

**Comment by ZenGround0** [comment]
Something I've noticed from fixing the flakiness: it is actually unnecessary and poor separation of concerns to wait until sealing completes.  Vouchers are valid after the deal duration is complete, which is well before sealing finishes.

Of course we will eventually need something that can handle waiting for a complete seal in order to test the edge cases of deal arbitration (specifically testing that when the sector is committed and the client erroneously arbitrates the miner can correctly end arbitration in their favor).

**Comment by anorth** [comment]
Ancient history
