### ISSUE TITLE
Hide non-consensus actor methods from processing

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#2973]
### Description

We have two slightly conflicting needs:

1. Keep actor methods binary compatible with spec so that we achieve consensus.
2. Allow the implementation to access chain state using the same logic as the actor methods.

The second need (and a few other needs) argue strongly for using actor methods to query chain state in the go-filecoin implmentation. Adding these methods to the spec, however, requires changes to the spec that don't actually affect the network implementation.

We can't simply add an actor method to the implementation without adding it to the spec, because attempts to call those methods from across the network would work on some implementations and fail with a method not found on others. This would cause consensus failures.

We need a way to flag actor methods that are needed by the implementation but not the networrk. This may be all methods that do not alter state. It's certainly hard to imagine why someone would want to pay for a message to go on chain that does not alter state when they can query their own chain for free.

When running state transitions, messages directed at query methods should behave exactly as if they do not exist.

### Acceptance criteria

1. Add a flag to `exec.FunctionSignature` that signals whether the method is part of the spec (consensus? query? specified? mutable?)
2. Add a parameter to `exec.VMContext` to signal whether the method is running as a query or part of message processing.
3. in `vm.Send` return a `ErrMissingExport` if we are in message processing and the method is only used for querying

### Protocol Changes

Once this functionality is in place, we should remove all read only methods from the spec.

**Comment by anorth** [comment]
At least some read-only methods are needed for the actors to interoperate with each other. As a (not great) example, the miner actor calls `getProofsMode` on the storage market. As another, the storage market's total storage power will be an input to miner collateral calculations. Query methods are generally useful, and the spec might not reflect all the utility.

Nevertheless, I agree in general that we need ways for non-actor code to inspect actor state and probably want to share code with actor method implementations.

If methods are omitted from the `Exports` list then I assume they are not invokable as messages and so not part of ABI compatibility. Presence in that list is the flag we desire. I think the question then becomes how to invoke the non-exported methods without going through the message-passing paraphanalia. Perhaps we need a code path to load an actor/state with a read-only VM context? Something similar to the current query-message, but that just returns an actor object instead of sending it a message. This would conveniently skip all the parameter encoding/decoding too.

**Comment by acruikshank** [comment]
I agree that read only methods will still be required for internal messages during normal message processing. As long as the spec can describe where the data lives and how it's used, it shouldn't need to specify exactly how one actor gets the data from another. This would leave the number, names, and calling mechanism for these methods up to the implementation.

I can see some ways we could remove query methods from `Exports` but they would require a rather large overhaul of our message processing system. Creating two separate lists would be pretty easy.

**Comment by anorth** [comment]
We discussed this in person. A few takeaways:

- To aid with versioning actors with protocol upgrades, there should be no (Go-level) exported free functions in actor packages. They should be made into methods so that an upgrade mechanism can select the right implementation
- Near term, we can get away with distinguishing non-exported (protocol level) methods with a comment in the exports list
- Longer term, we can implement something more direct and efficient than the current `queryMethod` wiring to fetch an actor implementation and invoke non-exported methods on it from worker code. This would bypass the protocol exports list, at which point we can remove the methods than should not be exported from it.
