### ISSUE TITLE
Ping is not available between nodes

### ISSUE THREAD

**Issue by a8159236** [filecoin-project/go-filecoin#3001]
I don't know if Filecoin requires all miners to use public network IP. I have many miners in different local area networks. They can ping between them, and some can't. In the case of unable to ping, it is also impossible to upload data to the other party. In addition, I found a new problem. At present, there are more than 200 nodes, but my miner can only connect to about 70 nodes. Is this normal?

**Comment by ZenGround0** [comment]
Hey @a8159236 though mining in production without a public IP will likely be a bad idea, by providing the autorelay network service Filecoin does not require a miner to use a public IP.  If a node has been running for more than 10 minutes without a public IP autorelay should kick in and give it a dialable address which should automatically allow them miner to be pinged.

It sounds like what you are discovering is that some mining node will enter the system, try it out, and then go offline without removing their information.  This is expected in the early state of our devnets.  Even when the system is in production there is no way to require that a mining operation is dialable by clients 100% of the time.  However there are a few things that make this much worse right now than it will be in the near-mid future.  

First right now we are implementing storage slashing which will evict a miner from the network if they stop submitting proofs of storage.  My guess is that all 130 of these nodes stopped accepting client networks because someone turned off the node.  In that case these miner addresses will all be gone from the blocktime within a day of node shutdown once storage slashing is implemented.  

The second things is that L2 miner discovery is pretty much non existent so you / your node has no better way than the blockchain to figure out who to store with.  This is something we are not prioritizing in the short term but plan to improve in the long term.

**Comment by a8159236** [comment]
@ZenGround0 Well, thank you very much.
