### ISSUE TITLE
Release 0.3.x

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3010]
The go-filecoin team will soon be cutting a new release and re-starting the user devnet.

Label: 0.3.x
When: Week of 8 July 2019

This release will include all development work since the 0.2 series in May. Work includes significant progress towards completion of the storage market actors, deal processing and management, on-chain proof-of-spacetime, payment channels & vouchers, node repo migrations and multiple sector sizes, plus loads of other smaller improvements. Release notes to be published will outline the changes in more detail.

As we approach the release cut, the GitHub milestone [go-filecoin 0.3](https://github.com/filecoin-project/go-filecoin/milestone/24) will tag issues and PRs we intend to include.

We’ll announce here and in slack #fil-dev with more timeline details once known.

**Comment by anorth** [comment]
The release branch is `release-0.3.0`. A release candidate tagged `test-devnet-0.3.0` has been deployed to the [test devnet](https://github.com/filecoin-project/go-filecoin/wiki/Devnets#test-for-infra-and-pre-release-testing) for verification. We have not yet validated that this network is fully functional, and since there's a public holiday for Americans, this may take a couple of days. We’ll cherry-pick fixes into the release branch and re-deploy to this test devnet if necessary.

If you’re new to go-filecoin, we recommend waiting until this release hits the user devnet before trying it out.

**Comment by anorth** [comment]
A new release candidate `test-devnet-0.3.1` has been deployed to the test devnet. We welcome any help validating this before we ship it to the user devnet.

**Comment by ZenGround0** [comment]
Release [0.3.2](https://github.com/filecoin-project/go-filecoin/releases/tag/0.3.2) is now stable on the user devnet.  Please upgrade your software to join the network.
