### ISSUE TITLE
[bug] Same actor and nonce but different cid 

### ISSUE THREAD

**Issue by steven004** [filecoin-project/go-filecoin#3052]
**Describe the bug**
This error has been seen in 0.2.4 and 0.3.0 version several times, when there are staged sectors waiting in line for sealing. 

`[0;37m16:29:28.595 [31mERROR [0;34m      node: [0mfailed to send commitSector message from t1kbn...yny to t2kab...xvi for sector with id 33....26: failed to add message to message pool: validation error adding message to pool: message pool contains message with same actor and nonce but different cid [0;37mnode.go:1110[0m`

And, I talked with some other miners, they got this too.

**To Reproduce**
Do not need to do any special steps, just send asks as fast as you can, and check the output log, then you will see this some time. 

**Expected behavior**
The nonce is increasing always, no same nonces for two messages in one miner's system.

**Version information**
Found in both test-devnet-0.2.2 and test-devnet-0.3.2

**Additional context**
Could there be race condition happened when multiple sectors for seal, especially when multiple workers are running?

**Comment by anorth** [comment]
Yes, I think I can see the potential race in `outbox.go`. 

I would expect you to receive an error from the message queue (not pool), "Invalid nonce %d, expected %d", and this would prevent you from adding the message to the pool. Nevertheless, I'll attempt to repro and fix.

**Comment by anorth** [comment]
Here's what I think is happening: it's not as simple as a race in the outbox.

The inbound message pool and outbound message queue are distinct structures. Outbound messages are held in the queue (per-actor) until they are observed in a heaviest tipset, and then forgotten. Nonces for new messages are calculated as the max of the actor's nonce, or one greater than the largest nonce for the actor in the queue.

The message pool stores *all* messages that are candidates for mining into a block, not just those sent by the node itself. They aren't organised into per-actor queues, but do have an index for efficient lookup of address/nonce pairs. Messages are also removed from the pool when observed in a heaviest tipset.

When a re-org occurs (the chain head swaps from one tip to another), messages in the losing chain effectively become "un-mined", and the actors state reverts to a prior state before messages in the new chain are replayed. The new chain/state may be missing some messages that the old chain/state had. Those missing messages are added back to the pool as candidates to be mined, but are *not returned to the outbound queue*. 

When a new message is sent in this state, the nonce will be calculated from actor state, the queue for that actor will be empty, and the calculated nonce will duplicate that of an "un-mined" message that returned to the pool.

What to do?
- We could return un-mined messages to the outbound queue too. This isn't obviously right, since most messages were probably not sent by this node and don't need tracking. But so long as unwanted queues are eventually cleaned out, it's simple.
- We could inspect the message pool too when computing nonces, but this gets a bit messy
- We could refactor the queue and pool such that the pool performs both functions, i.e. with an embedded per-actor queue and an index for quickly looking up messages (nonces) from a single actor. This may be a good opportunity to store the messages in mining-priority order, which is currently recalculated every time.

The first option is probably expedient. The third might be the right long-term direction, but is a bit of work. @acruikshank thoughts?

**Comment by anorth** [comment]
This error is causing some tests to be flaky.

**Comment by anorth** [comment]
I'm factoring out the node handling for a new head tipset so I can write a test demonstrating this, and then fix it.

**Comment by maris205** [comment]
the version 0.5.6 also meet this bug:
16:56:53.219 ERROR       node: error in handler github.com/filecoin-project/go-filecoin/node.(*Node).processMessage-fm for topic /fil/msgs/alpha2: validation error adding message to pool: message pool contains message with same actor and nonce but different cid no
