### ISSUE TITLE
[bug] timeouts when proposing storage deal for large piece

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#3093]
Note that this bug manifests only when using 256MiB or larger sectors (and pieces).

A storage deal proposal, sent to the storage miner from a storage client, includes a piece commitment which is computed by the storage client. When proposing a deal which references a piece which is 254MiB in size (to a miner which pledges 256MiB bit-padded sectors), the client pauses for a time and then sees a `context deadline exceeded` error.

When generating a piece commitment for a 254MiB piece (the largest that can fit into a 256MiB sector), `GeneratePieceCommitment` can take over 4 minutes to return. When generating a piece commitment for a 1016MiB piece (the largest that can fit into a 1GiB sector), `GeneratePieceCommitment` can take over 18 minutes to return (on my laptop, a fancy new MacBook Pro).

Changing the setup context timeout is easy, which would eliminate this error. The fact remains that the client would have to spend a significant amount of time generating a piece commitment _before sending their proposal to the miner_. If the miner were not dialable at the end of the 18+ minutes, the storage client's proposal would fail. The storage client would have wasted a lot of time computing a piece commitment which they did not ultimately use.

**Comment by laser** [comment]
The failure mode described here is at least partially attributable to [this upstream rust-fil-proofs](https://github.com/filecoin-project/rust-fil-proofs/issues/749) bit-padding issue.

**Comment by travisperson** [comment]
@laser I don't think I quite understood this when you mentioned it in slack, I was looking for nodes panicing which I didn't see. However, because we do propose deals we are seeing this timeout occur which stops the nightly deployments.

You may it sound like there is a timeout we might be able to increase that would result in the `propose-storage-deal` not to timeout?

**Comment by anorth** [comment]
As discussed with @travisperson let's expose the piece-processing timeout as high up as we can, ideally to the CLI. It should be separate to the timeout subsequently on contacting the miner, which can remain short.

The final paragraph is important but distinct and not as pressing. In particular, since the same piece commitment can be used to send a proposal to *another miner*, it seems like more of a UX problem around caching that commitment somewhere.

**Comment by travisperson** [comment]
We've removed the timeout that was occurring during due to `GeneratePieceCommitment` in #3115. The timeout is now only used to wait for the payment channel.
