### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by LYT1272478208** [filecoin-project/go-filecoin#3105]
autonat: Discovered AutoNAT peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY notify.go:33
16:14:27.613  INFO       node: processMessage(): validation error adding message to pool: message nonce (413) is too much greater than actor nonce (0) node.go:999
16:14:28.116  INFO       node: processMessage(): validation error adding message to pool: message nonce (414) is too much greater than actor nonce (0) node.go:999
16:14:28.519  INFO       node: processMessage(): validation error adding message to pool: message nonce (415) is too much greater than actor nonce (0) node.go:999
16:14:33.005  INFO       node: processMessage(): validation error adding message to pool: message nonce (6941) is too much greater than actor nonce (0) node.go:999
16:14:37.347  INFO       node: processMessage(): validation error adding message to pool: message nonce (3589) is too much greater than actor nonce (0) node.go:999
16:14:51.070  INFO       node: processMessage(): validation error adding message to pool: message nonce (3539) is too much greater than actor nonce (0) node.go:999
16:14:52.053  INFO       node: processMessage(): validation error adding message to pool: message nonce (553) is too much greater than actor nonce (0) node.go:999

**Comment by frrist** [comment]
Thanks for the issue report. Could you include details below so we can investigate?

Please reopen this issue once more info is available, and we'll be happy to take another look.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Run this command '...'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots or Console Output**
If applicable, add logging output or screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [if applicable, e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
