### ISSUE TITLE
Flaky tests due to "bind: address already in use"

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3145]
`TestMpoolLs` failed on master [here](https://circleci.com/gh/filecoin-project/go-filecoin/24134#tests/containers/2) with error

```
...bind: address already in use...
...
filecoin node failed to come online in given time period (10 seconds); last err = Get http://127.0.0.1:40787/api/id: dial tcp 127.0.0.1:40787: connect: connection refused
```

**Comment by ZenGround0** [comment]
Same error causes failure in `TestDhtFindPeer` here: https://circleci.com/gh/filecoin-project/go-filecoin/23984#tests/containers/2

**Comment by anorth** [comment]
The test logs show the same port being used for both the swarm listen and the command API, with one of those thus failing to listen on the port.

The problem is this code in `testhelpers/commands.go`. 
```
	cmdPort, err := GetFreePort()
	if err != nil {
		t.Fatal(err)
	}
	swarmPort, err := GetFreePort()
	if err != nil {
		t.Fatal(err)
	}
```
It sometimes gets the same port for both (I'm surprised it's not all the time!). This pattern would be flaky even if it were only fetching one address, in environments with many listening processes (like CI).

I will attempt to remove the command port, and maybe also the swarm port, by allowing the OS to assign a port when listening and then reading the address out of the repo.
