### ISSUE TITLE
[bug] seal sector pip verification failed

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/go-filecoin#3161]
Commit: 56110c4f169f246c747def0693401cfc3a023e29

Describe the bug:
failed to seal sector with id ***: unrecoverable error: pip verification sanity check failed

**Comment by travisperson** [comment]
I've ran into this last week and earlier this week, but I believe the update in #3128 fixed it. Could you try a more recent version and see if you run into the issue again?

**Comment by Lhehe** [comment]
> I've ran into this last week and earlier this week, but I believe the update in #3128 fixed it. Could you try a more recent version and see if you run into the issue again?

Is version 0.3.2 a bug that really can't be solved?

**Comment by travisperson** [comment]
Piece inclusion proofs are not in 0.3.2 so I'm not sure what you are asking. Could you clarify what bug you are referring too?

**Comment by Lhehe** [comment]
> 片段包含证明不在0.3.2中，所以我不确定你在问什么。你能澄清一下你所指的是什么bug吗？
My storage order shows that complete has been very many, but Storage on the test network has remained unchanged. What is the most likely reason for this problem?

**Comment by travisperson** [comment]
There are few reasons this could occur.

The first is that not enough time has passed. Currently it takes 3 proving periods for additional power to show up. This has to do with the fact that PoSt generation is much faster than sector sealing. I've talked a little about this when answering another question [here](https://github.com/filecoin-project/go-filecoin/issues/3077#issuecomment-512117118).

Another possibility is that one of your `submitPoSt` actually failed for some reason. There is an open issue to track one failure we've seen (https://github.com/filecoin-project/go-filecoin/issues/3019).

A less likely but still possible issue is that you actually created so many sector commitments that you hit one of two bugs, though I'd assume if you haven't seen your power increase over the initial amount you are not hitting these bugs.

The first was that we were proving over sector commitments and not the proving set. This was fixed in https://github.com/filecoin-project/go-filecoin/pull/3067. The second issue is is semi related, currently we only prove over two sectors per PoSt. Meaning for every two sectors a PoSt must be generated. At the moment this isn't a huge issue at first due to how fast PoSt is. However, as time goes on, and in conjunction with #3067 it takes longer than a proving period to generate all of the PoSt required.

**Comment by Lhehe** [comment]
> 这可能发生的原因很少。
> 
> 首先是没有足够的时间过去。目前需要3个证明期才能显示额外的电量。这与PoSt生成比扇形密封快得多的事实有关。在回答[这里的](https://github.com/filecoin-project/go-filecoin/issues/3077#issuecomment-512117118)另一个问题时，我已经谈过这个问题。
> 
> 另一种可能性是你`submitPoSt`的某个实际上由于某种原因失败了。有一个未解决的问题是跟踪我们看到的一个失败（[＃3019](https://github.com/filecoin-project/go-filecoin/issues/3019)）。
> 
> 一个不太可能但仍然可能的问题是你实际创建了如此多的部门承诺，你遇到了两个错误中的一个，尽管如果你没有看到你的功率增加超过初始数量你没有遇到这些错误。
> 
> 首先是我们证明了部门的承诺，而不是证明。这已在[＃3067](https://github.com/filecoin-project/go-filecoin/pull/3067)中修复。第二个问题是半相关的，目前我们只证明每个PoSt超过两个扇区。每两个扇区的含义必须生成一个PoSt。由于PoSt的速度有多快，目前这不是一个大问题。但是，随着时间的推移，与[＃3067](https://github.com/filecoin-project/go-filecoin/pull/3067)一起生成所需的所有PoSt需要比证明期更长的时间。
After I created a new node, the storage proved to be all right now. I feel that my CPU or bandwidth is not enough, or can you tell me what the most basic hardware for testing is?

**Comment by travisperson** [comment]
Been seeing this again, most recently when testing against `nightly-26850-9547cd`.

**Comment by diwufeiwen** [comment]
> 9547cd

staging-devnet-0.4.1 is also,I checked that the filecoin-proofs referenced in the sector-builder is 0.4.0. This version is problematic. It is recommended to switch to 0.5.0.

staging-devnet-0.4.1: sector-builder-ffi/Cargo.toml
filecoin-proofs = "0.4.0"
filecoin-proofs-ffi = "0.5.0"
logging-toolkit = "0.4.0"

No error: sector-builder-ffi/Cargo.toml
filecoin-proofs = "0.5.0"
filecoin-proofs-ffi = "0.6.0"
logging-toolkit = "0.5.0"

**Comment by diwufeiwen** [comment]
@travisperson  After I modified the version, PIP didn't report error, but failed when applying the message:
ApplyMessage failed: Could not stage memory chunk: State could not be decoded SignedMessage cid=[bafy2bzaced66vhn4i4ahkapfcndlzdhq7ia5takavpnaukdhr26narivnghn6]: {
  "meteredMessage": {
    "message": {
      "to": "t2jd22iwp4iym2y34d7aw7qsvc35zmsic7rszwcwy",
      "from": "t1k5wpx7h4juhkgf7xwimsc7a7v4tyfswtzmnqkeq",
      "nonce": "2",
      "value": "0",
      "method": "commitSector",
      "params": "hUaHgICAkBBYIEzkvIFi7oSWA7zM5R+v3MSobT8OAps15tuZU7/biRQOWCAcJRNHdoHNjJn0dICxY5mUST07sthWadXzD72JBrMjGlggfvJpi/QVxQBlzkPHic/I6GQtGkxCioNbkxe0+FNLRWlZAYCMEEeXTPtLBA5VPBYe4RFzYbGwlsrqGJzHWtTAlANpR2siXYET7mbydtxtf2WGITuJ+dAsh2qebNjHVZW3D5Je2lvP9AYll06H8orF8s2XfTYspjgBh7yX2/Ub9lE+EH0ZsPKb5RSvgphLq2WUO6Fpf9R2wKMFXYAyx65ZhV2miNZB4smn9a/oNwM/NXIjz7K3dxrtsWzUZeYXJOqMAtpbbVLHJnghy5LBMb6hOK648qZmusLCTSXXTNvfTyATZhuUKhnZt02cvk5ofqvIhIfrHqPXmFpRnGr5BvcpiSkK0Eqw9IscHCnFf34UxjfDYiGxcZbQucQ6S6nO8fNv/hCXOp/hwx4Nbt9iduc2HmWbSwHulxZOzlwDqMi3ZfQ3/9YMGRwQKH8PhQ0DJEnmTBoNjnXO0bUqea1ONY1frH3EwNLAmG28a/GexyKuhyJ6TGirxNVNP85b+axDEMfa+hZgIseq7phbElH6uwX2BMbOo3+Odha0argpzUk0iGn+d88="
    },
    "gasPrice": "0.000000000000000001",
    "gasLimit": "300"
  },
  "signature": "+voppXBSJWU08AJ+caZJh6+unNL8dk3D28z+qWQanjNYUPKVMjV4GVqyf2Tm5E6JPA+aTeGMe2q46gLGbbzKhwE="
}
