### ISSUE TITLE
Extended graphsync-based chain sync tests

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#3232]
### Description
Chain sync is a security-critical function and needs robust testing. The new graphsync-based syncer is great, but we need more confidence in it.

Extend unit and/or integration tests to cover:

- [x] partial responses
    - [x] missing Messages/MessageReceipts collection
    - [x] missing one block in multi-block tip (in recursive fetch)
    - [x] stopping after every height in [1, 5] in a recursive fetch (to catch batch edges)
- [x] a Block decodes but is not syntactically valid
- [x] the structure pointed to by Block.Messages/MessageReceipts does not decode
- [x] the structure pointed to by Block.Messages/MessageReceipts is not syntactically valid (there is no validator for messages implemented yet)
- [x] more to come...

In order to make these tests concise, I expect it'll be worth some effort extending the existing mock structures for more power and clarity.

Note: when the message/receipt structures themselves become trees, we'll also need to test for partial response of those.

### Acceptance criteria
- the graphsync-based fetcher is thoroughly covered by tests

### Where to begin
Existing tests are a good start

@hannahhoward

**Comment by hannahhoward** [comment]
@anorth for validation -- is it reasonable to produce a mock validator that errors on a CID? this strikes me as the "unit test-ey way to do this"

**Comment by anorth** [comment]
My first thought is that it's probably easier to use a real validator and
produce a block, e.g., with no state root CID. But ok either way.

**Comment by hannahhoward** [comment]
@anorth another follow up -- for "not decodable blocks" -- unfortunately using a loader that loads different blocks for certain CIDs with mock graphsync is not going to work.

the problem is the block store -- you can use a fake loader to get different blocks, but once you put them in the block store, they're only gonna come out of the block store with their actual CID.

it also doesn't match the way graphsync actually works and wouldn't happen this way in the real world -- one of it's guarantees is if a query is made, and the remote sends you bad data, it's gonna make sure that data doesn't get stored.

it feels like instead what I need to do is actually allow you to actually build bad chains and blocks where the messages/receipts are not decodable inside the chain builder. does this seem reasonable?

I want to do something like add the following methods to chain builder:
- BuildOnBadParent(parent TipSetKey) (as opposed to tipset)
- and for the block builder SetBadMessages(MessageCID, MessageReceiptCID)

**Comment by anorth** [comment]
For such one-off cases, it might be easier to just manually construct a block referencing one from the Builder as its parent. 

Maybe such tests are easier to construct as an integration test, where we can send the bad data over the "network" rather than try to pretend graphsync would be so broken?
