### ISSUE TITLE
[bug]localnet can not sync to local chain under staging 0.4.1 version

### ISSUE THREAD

**Issue by embedSky** [filecoin-project/go-filecoin#3241]
**Describe the bug**
I run the localnet with release version staging 0.4.1 . And then I create a new node to connect the localnet but the new node can not sync to the localnet chain .find err
```
5:01:20.444  INFO       node: error handling tipset from hello {peer=QmUhxszVnCnyTwxQMUxsqZ442pUUAzuZcNb8ApHmru1RTF height=145 head={ bafy2bzaceaivxtbnj26mw3xupugib57zq6r4vqriail4gnyw6a6pnzv3lufwe bafy2bzacedcqn32v4zon5siqnmsgbodoelkmk5ojtijgwrjwymgkpih32zk3c }}: block bafy2bzacecttlqbs2etcftklx3kq4bnl2nejpkv6yh3fk65tu4ojsobejbzzo with timestamp 1565850980 generated too far past parent, expected timestamp < 1565851000 node.go:573
```

**localnet config**
go-filecoin version:0.4.1(5427eb7a0cc9558e4c61eeeaab9cc58408fa8931)
localnet cmd:
```
./localnet  \
        -blocktime=10s \
        -miner-count=1 \
        -small-sectors=true \
        -shell
```

**Comment by embedSky** [comment]
I have try to modify the blocktime to 30s and then run the localnet again. the new node sync to localnet chain success

**Comment by travisperson** [comment]
Does the log you provide come after you exit the localnet shell, or did you setup a stand alone node and connect to the localnet? If it's the later I'd guess that when you started the daemon you may of left off the block-time, though without know how you setup the node I'm not positive.

I suspect that it's not from the localnet shell node just because I believe the chain has to sync before the shell will even open.

> timestamp 1565850980 generated too far past parent, expected timestamp < 1565851000

Strange error considering that `1565850980` is less than `1565851000`. I think the error is actually suppose to say that it wants a time _greater_ than the `1565851000` value.

**Comment by embedSky** [comment]
@travisperson I setup a stand alone node and connect to the localnet. I have find the reason. my localnet block time is 10s but my new node default 30s , thanks for reply.
