### ISSUE TITLE
[bug] pub const POST_SECTORS_COUNT: usize = 512 very unreasonable.

### ISSUE THREAD

**Issue by embedSky** [filecoin-project/go-filecoin#3267]
**Describe the bug**

the code 
```
pub const POST_SECTORS_COUNT: usize = 512;
```
in moudle rust-fil-proofs I think the value 512 is very unreasonable .

**Comment by embedSky** [comment]
it cost too much cpu and memory .

**Comment by ZenGround0** [comment]
Hey @embedSky the first thing to note is that this issue belongs in the rust-fil-proofs repo, it is it's own project with its own set of issues and people specialized to respond to them: https://github.com/filecoin-project/rust-fil-proofs

Next, the PoSt construction used by go-filecoin is at this point a soon-to-be deprecated prototype.  A new construction is under development to address lots of issues, so it is certainly the case that you will find many unreasonable things when looking at the code. 

Finally please note that we 100% appreciate feedback on how the design of the protocol and its implementation affect the reasonability of its use.  However this feedback can only help us address your concerns if you explain the problem.  When you say "I think the value 512 is very unreasonable" this does not help us understand the issue or put your feedback into context.  Are you concerned about snark proving performance because you think 512 is too high?  Are you concerned about chain tx throughput because you think 512 is too low?  What sector sizes are you considering in your analysis? etc.

Please re-open this issue in rust-fil-proofs with a more complete explanation of your concern and  the team will address it there.
