### ISSUE TITLE
Persistent journal for event recording, inspection

### ISSUE THREAD

**Issue by anorth** [filecoin-project/go-filecoin#3269]
### Description
For a couple of different reasons now, there's a desire for a system for recording some event-type information for subsequent inspection:
- #2443 recording CLI commands to keep track of piece->miner mappings (and other info)
- #3230 recording messages that enter and exit the outbox (for testing and manual inspection)

In both cases:
- the events should be persisted to disk and survive node restarts
- the events carry structured information
- data size is fairly small

I think this calls for a *journal* of structured (but schema-free) data, persisted to the repo. I am avoiding calling this a log because, unlike application logs, we don't need levels, formatters, and all the configuration options thereby made possible.

I propose a journal facility for recording events:
- each event has a topic (string) and payload (struct serialised to JSON)
- each topic is persisted to a file in `repo/journal/<topic>`, one JSON object per line
- the journaller might add a `timestamp` to every record for convenience

In the near term, the interface to this can probably be a simple one-method interface, 
```
  Record(topic string, payload interface{})
```
Errors are unlikely to be actionable, so the journaller can log them but allow the caller to move on. If we later implement an event bus (#2309) that might be an even lighter coupling way of emitting events.

For FAST testing, we also need a mechanism to read the journal file (ideally, streaming like `tail -f`). The files would be human readable, so we probably don't need to add any CLI access.

@travisperson @frrist @acruikshank I'd welcome your thoughts and critique here.

@deaswang you have previously proposed something similar. After we get some feedback on this proposal, I'd welcome your contributions to the implementation.

### Acceptance criteria
TBC

### Risks + pitfalls
Do we really need this? Is there a better way to solve the motivating problems?

**Comment by acruikshank** [comment]
In general, I think the format is good. I think adding a timestamp will be essential, since any type of forensics will require us to interleave topics to understand the sequence of events. I can make some arguments for putting all the topics in a single file, but, with timestamps, it becomes just a matter of having the right tools.

I don't think this is how we should handle piece->miner mappings for reasons described in #2443.

I do think the command history (hopefully command+API history soon) will be useful for troubleshooting, so my concerns about the above are somewhat irrelevant to this discussion.

I do like the idea of inspecting the message log (or the command log) for FAST testing, and having a well specified format, structured logs and some tooling around that should make that straightforward, so 👍.

**Comment by frrist** [comment]
+1 to timestamps and ndjson.

I think having a journal of anything a node wants to get on chain will improve debuggability since it can be hard to track down messages that fail to apply. I imagine a VM journal being quite useful for certain cases.  

I do understand this is different than _logging_ and I don't think we should allow the contents of log messages to influence the behaviour of software. _Butttt_ I am hesitant to create something new that basically does a more specific type of logging :weary:.

**Comment by travisperson** [comment]
This sounds good. FAST can provide a way to receive the entries for a topic and we can build some functionality around this to enable whatever tracking we need for tests.

**Comment by anorth** [comment]
> I can make some arguments for putting all the topics in a single file, but, with timestamps, it becomes just a matter of having the right tools.

I could go either way on this. The journaller can add the topic field to the payload along with timestamp if they go to a single file. Filtering a single file is probably simpler than merging two or more files, so shall we take that simple default?

**Comment by frrist** [comment]
In the interest of not writing too much of this ourselves how would we feel about wrapping an existing logging framework with the interface described above? [Zap](https://godoc.org/go.uber.org/zap) is perfectly capable of writing structured data to a file, and can be configured such that it only prints the time and message of an entry. 

Rough sketch of what this could look like [here](https://gist.github.com/frrist/ade8a254da8abf8412990497a7b378a3)

**Comment by anorth** [comment]
I'm ok with that, or with writing to file ourselves. I'll defer to the implementer.

**Comment by anorth** [comment]
@deaswang I think we have enough agreement here that you could safely start.

Please break this work into self-contained pieces that we can review in stages, rather than a giant PR that does everything. That way, if reviewers have feedback and suggestions, they are easier to incorporate.
