### ISSUE TITLE
when i run this 0.4.3 release, i get this error

### ISSUE THREAD

**Issue by LYT1272478208** [filecoin-project/go-filecoin#3270]
My peer ID is QmPuwUwWgV6GXhhhN6d7RR7VnXrJuGzQJ6xfx81HfkrZaL
Swarm listening on: /ip4/127.0.0.1/tcp/6000
Swarm listening on: /ip4/192.168.0.103/tcp/6000
Error: error loading head tipset: failed to get block bafy2bzaceaj2y6z5ijufp7lsljtr3354xxg5dujx3rg3wrr7jix3zhpqju7ps: unmarshal error: cannot assign <[:5> to slice field

how to deal with it ?

**Comment by travisperson** [comment]
How did you initialize your node? Most likely you are using the wrong genesis. There is no 0.4.3 network really running at the moment.

**Comment by frrist** [comment]
Thanks for the issue report. Could you include details below so we can investigate?

Please reopen this issue once more info is available, and we'll be happy to take another look.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots or Console Output**
If applicable, add logging output or screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [if applicable, e.g. chrome, safari]
 - Version [e.g. 22]
 - Output of `go-filecoin inspect all`

**Comment by OdysLam** [comment]
I also get an error when running the latest version of filecoin. How can we participate in a working filecoin dev-net?

`Error: Could not Init Node: link value was empty`
