### ISSUE TITLE
[bug]Cannot apply for FIL in Release v0.4.6

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/go-filecoin#3316]
Describe the bug
http://user.kittyhawk.wtf:9797,Cannot apply for FIL.

curl -X POST -F "target=`./go-filecoin address ls`"  "http://user.kittyhawk.wtf:9797/tap" | cut -d" " -f4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   267  100    85  100   182    113    242 --:--:-- --:--:-- --:--:--   242
bafy2bzacebeqrwbw4ip7ge4gjw6zcgy4ru5b6eplj7eqbydb63drxv2txt3mk
 ./go-filecoin wallet balance `./go-filecoin address ls` 
0

Version information
Release v0.4.6

**Comment by Lhehe** [comment]
After I retried the initialization node, I also encountered this problem.

**Comment by ckxaaa** [comment]
metoo

**Comment by ttt789** [comment]
这是真的  我也是

**Comment by muronglaowang** [comment]
Is your block height the latest height?

**Comment by steven004** [comment]
@pooja, I believe this is blocking the network trial. Could someone look into it?

**Comment by anorth** [comment]
Using the UI, I see the response is "failed to send funds"

**Comment by anorth** [comment]
The page reported a success for me just then, so it works sometimes. And there are certainly some miners submitting posts.

I note that blocks have lots of messages like this. I initially discounted this as just an error in someone's forked implementation, but maybe it's affecting message throughput or something?

```
15:57:19.205  INFO consensus.: ApplyMessage failed: sector already committed at this ID SignedMessage cid=[bafy2bzacedfxgiok6zezlewceubi4bxhq67phigekdniodghd3redg5deb7u4]: {
  "meteredMessage": {
    "message": {
      "to": "t2l3mvbxn5vidkvzswyf3icl7bneuuyseau2kyvya",
      "from": "t1eqfffirfoyyjrdzlbmpghbd3yn4zaflqsm5a5lq",
      "nonce": "412",
      "value": "0",
      "method": "commitSector",
      "params": "hUKNAVggP2FRTKZ9dr+NQAbP+Yo461P62CaD0vgJH1dVldwV3ShYIPeINp7x11cmiYhKm+JDuvQLYyV4MIAH2PkPrcjxf5hZWCDi+9+GWswdF3feHxan6wU/Wl4ypprEPcR7oSbXzfPJPVkBgKDGv+zHFA2dpjZsnKo9a3KYW6t9k1m6Q0ro4zH96j34TFBeSX+ILu14b2hGlEfE9YChOatr1h9ekZv0R3MAHLhf5TF8Z/yy9YuzFE0Buec8LqYjVByvHY+5/3fGYfTmsg6er59Mrjfi8VQV75ZFskjx9BkwmFKyOT+4Qnt1RRHBwRdy09GG+PHtDMASe7ZFiIXzHBFG86Z8+f67Hm8fYSYas2O1I3cwmnl0GlodhqNkqUeCfQI1sI/V4OVhql7VFZfRy94pKL8GcXqxcQKMNXkzTlgNCHGlFK+ZLL+UH6du5nylzIftUSVUw09i4ytBF7H7DniNcmp+9SE4d5xD0Iocz4MmynEtNoRIOPgjqHqTwRUUJA6m4DuiYjlYTmvP1wSSjCap8W1BgabDPZ0fdj9Z5aab0Pt0m6jU9Hfc8ThL9ksuwq5Zoc12PnAuY7PBEaKiGZeVemcm1gC8qc/PsfBygAQIE4sYgdb60Z+hk9RNEfAnnjXHDWUqGTckRMPZoA=="
    },
    "gasPrice": "0.000000000000000001",
    "gasLimit": "300"
  },
  "signature": "vB9QPLg7uEv9fB97BjKcsMMk0vTc1XH+ZjwrwGZ0/M8ohVZmIdN8uXZYd7x6pEk35fcjCF98h4Q1fteaTncw5QA="
} processor.go:339
```

**Comment by jimpick** [comment]
Me too, but it eventually worked...

```
filecoin1@nuc:~$ curl -X POST -F "target=${WALLET_ADDR}" "http://user.kittyhawk.wtf:9797/tap"
failed to send funds
filecoin1@nuc:~$ curl -X POST -F "target=${WALLET_ADDR}" "http://user.kittyhawk.wtf:9797/tap"
failed to send funds
filecoin1@nuc:~$ curl -X POST -F "target=${WALLET_ADDR}" "http://user.kittyhawk.wtf:9797/tap"
failed to send funds
filecoin1@nuc:~$ curl -X POST -F "target=${WALLET_ADDR}" "http://user.kittyhawk.wtf:9797/tap"
failed to send funds
filecoin1@nuc:~$ curl -X POST -F "target=${WALLET_ADDR}" "http://user.kittyhawk.wtf:9797/tap"
failed to send funds
filecoin1@nuc:~$ curl -X POST -F "target=${WALLET_ADDR}" "http://user.kittyhawk.wtf:9797/tap"
failed to send funds
filecoin1@nuc:~$ curl -X POST -F "target=${WALLET_ADDR}" "http://user.kittyhawk.wtf:9797/tap"
failed to send funds
filecoin1@nuc:~$ curl -X POST -F "target=${WALLET_ADDR}" "http://user.kittyhawk.wtf:9797/tap"
Success! Message CID: bafy2bzacealkhmyxafszejfe4jjcssoxeqqysb6nmivsumbnrl5axrdvrngac
```

**Comment by jimpick** [comment]
Update: Even though I got that Message CID 15 minutes ago, my wallet hasn't been credited with a balance yet. My chain appears to be synced. Might be a related issue maybe?

**Comment by birdmanscn** [comment]
Same problem here. I tried many times,  sometimes it's Success! , sometimes it failed.   
But no matter it's successful or not, my balance maintained 0.

Also, when I did 
`
MESSAGE_CID=`curl -X POST -F "target=${WALLET_ADDR}" "http://user.kittyhawk.wtf:9797/tap" | cut -d" " -f4`
`
It returned like this differently everytime.
`
   % Total     % Received % Xferd  Average Speed      Time    Time     Time  Current
                                                         Dload  Upload      Total    Spent    Left    Speed
100   203  100        21  100    182         20        175   0:00:01  0:00:01 --:--:--   176
`
`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   267  100    85  100   182    104    224 --:--:-- --:--:-- --:--:--   224

`

**Comment by swanduron** [comment]
The web page seems not stable in sometime. If someone gets error message likes "failed to send funds", another try is necessary in short times.

**Comment by sunhansong** [comment]
So is there a solution to it now? I've got the Success message, but my balance is still zero.

**Comment by jimpick** [comment]
I'm not on the Filecoin team, but my understanding is that there will be a new 0.4.7 release coming out soon that will fix this issue.

**Comment by zfogg** [comment]
+1

**Comment by ZenGround0** [comment]
We have some ideas about the root cause of this.  

The faucet website/backing filecoin node sending messages seems to be working just fine.  The issue appears to be caused by network partitions resulting from recent changes to the syncing code.  Because of bugs in the syncing code block fetching occasionally stalls for one minute and prevents nodes from processing new blocks.  Sometimes nodes behind this partition mine on their own chains which leads to forking.  Geographically partitioned nodes (like the bootstrappers generating the messages) appear to be extra susceptible to being behind or on a fork rather than at the latest head.  

It is still unclear to me why faucet messages are not propagated widely enough to make it onto all forks as they are not effectively partitioned by the syncing bugs.

devnet-staging-0.4.7 (currently on staging) fixes the worst fetch-blocking bugs, though we can't be sure how completely this addresses this bug until we have a more realistic network.  We are still deciding whether we will deploy this patch to user this week, or wait for the upcoming 0.5.x release.

**Comment by wyblyf** [comment]
V0.5.6  Same problem +1

**Comment by OdysLam** [comment]
V0.5.6 Same problem +1

**Comment by 15000402842** [comment]
please give me your T2 address ！



    


            On 10/02/2019 16:46, Odysseas Lamtzidis wrote: V0.5.6 Same problem +1

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/filecoin-project/go-filecoin/issues/3316?email_source=notifications\u0026email_token=AI7RFHZ2SVETNACEJLMUJP3QMRNUNA5CNFSM4IR6B2K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAEAVZA#issuecomment-537397988",
"url": "https://github.com/filecoin-project/go-filecoin/issues/3316?email_source=notifications\u0026email_token=AI7RFHZ2SVETNACEJLMUJP3QMRNUNA5CNFSM4IR6B2K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAEAVZA#issuecomment-537397988",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by OdysLam** [comment]
t1hieq4dc3y3tlptg3xy2nb4ruczlomcixak2we4a, 
t1zssqje556qtduf6nh2mkbdza2acsrutqb3pnz2a

2 filecoin nodes

**Comment by 15000402842** [comment]
Done ，2000 Fil



    


            On 10/02/2019 18:31, Odysseas Lamtzidis wrote: t1hieq4dc3y3tlptg3xy2nb4ruczlomcixak2we4a,
t1zssqje556qtduf6nh2mkbdza2acsrutqb3pnz2a
2 filecoin nodes

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/filecoin-project/go-filecoin/issues/3316?email_source=notifications\u0026email_token=AI7RFH673V5ZTXUEBXJMBGLQMR2BDA5CNFSM4IR6B2K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAEJQMI#issuecomment-537434161",
"url": "https://github.com/filecoin-project/go-filecoin/issues/3316?email_source=notifications\u0026email_token=AI7RFH673V5ZTXUEBXJMBGLQMR2BDA5CNFSM4IR6B2K2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAEJQMI#issuecomment-537434161",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by OdysLam** [comment]
For some reason, FIL just disappeared

**Comment by jimpick** [comment]
@OdysLam Same happened to me. I was informed that currently the devnet is partially broken due to a flaw / incomplete implemention that somebody was exploiting, which the team will be fixing after they get back from their planning week. Some context here:

https://github.com/filecoin-project/go-filecoin/issues/3502

**Comment by walkerxin** [comment]
V0.5.6 same problem and it's even not the return string.
And there is ubnormal my node height is bigger than that is shown in stats page.
![ubnormal block height](https://user-images.githubusercontent.com/44486634/66175004-696ae800-e68a-11e9-96a8-43c02c8288a4.png)
So is the failed result reason?

**Comment by OdysLam** [comment]
@jimpick Thank you so much for this info, it saved me a ton of time from trying to figure out if I was doing something wrong.

Cheers :)
