### ISSUE TITLE
Error in starting mining

### ISSUE THREAD

**Issue by Lhehe** [filecoin-project/go-filecoin#3509]
When I st# go-filecoin mining start
Error: failed to get miner actor: no actor at address t2m6pcghqojqc7va5jbxch3xti6nrh7dct2ijg36a: actor not found

**Comment by maobisheng** [comment]
I also found this issue just now, but it works few minutes later.

**Comment by travisperson** [comment]
The message which created your miner was probably dropped due to a bug that occurs during reorg. More information can be found in https://github.com/filecoin-project/go-filecoin/issues/3508.

To fix this issue on your current node you will need to run the following command and then restart your node.

```
./go-filecoin config mining.minerAddress empty
```
