### ISSUE TITLE
After my daemon went offline,I rerun the daemon,this error occurs

### ISSUE THREAD

**Issue by muronglaowang** [filecoin-project/go-filecoin#3510]
I run this commandgo-filecoin daemon --repodir=/fil/f 

9:59:16.937 ERROR       node: setup mining failed: failed to initialize sector builder: failed to get sector size for miner w/address t23ke54rvfe5bkaylu5hj5t6hrzpn4hdlzz7a2kei: query and deserialize failed: 'getSectorSize' query message failed: querymethod returned an error: failed to get To actor: actor not found node.go:219
Error: failed to initialize sector builder: failed to get sector size for miner w/address t23ke54rvfe5bkaylu5hj5t6hrzpn4hdlzz7a2kei: query and deserialize failed: 'getSectorSize' query message failed: querymethod returned an error: failed to get To actor: actor not found

**Comment by travisperson** [comment]
This is due to an error in the way we add messages back into the message pool after a reorg. See https://github.com/filecoin-project/go-filecoin/issues/3508.

You should be able to recover your node by unsetting the miner address, if you want (this just lets you keep the chain data you already downloaded). To do this you will want to stop your node and drop the `miningAddress` field from the `mining` object. You should then be able to start your node backup and issue another `miner create`.
