### ISSUE TITLE
Can't propose storage deal - no actor at address<>

### ISSUE THREAD

**Issue by OdysLam** [filecoin-project/go-filecoin#3526]
Whenever I propose a storage deal, the daemon informs me that there is no actor associated with my address.
```
Error: error creating payment: no actor at address t1hieq4dc3y3tlptg3xy2nb4ruczlomcixak2we4a: no actor at address t1hieq4dc3y3tlptg3xy2nb4ruczlomcixak2we4a: actor not found
```
Devnet 0.5.6

**Comment by OdysLam** [comment]
New error: `Error: querymethod returned an error: failed to get To actor: actor not found`

**Comment by eshon** [comment]
@OdysLam - The Devnets are having issues. It’s been a mix of an attacker (the miner with the most power) forking the heaviest chain because weighting hadn’t been fully implemented yet by the go-filecoin team). This causes chain reorgs and messages are dropped because of another bug: https://github.com/filecoin-project/go-filecoin/issues/3508  Might be best to wait until the fixes have been deployed which should be soon.
