### ISSUE TITLE
What's the purpose of malicious node "ForcePool"

### ISSUE THREAD

**Issue by merced** [filecoin-project/go-filecoin#3528]
Once again this guy fork attacked the net, and stop progressing the chain for 10 hours til now. Want to demonstrate the flaw? Already did in your previous attacks. So what's the point of destructing the chain again and again? It's really frustrating for regular miners!

**Comment by zhangjy-1984** [comment]
@steven004 Why are you attacked the net again and again?

**Comment by steven004** [comment]
@zhangjy-1984 , It is a rudely offensive question to me. I want you know this. I do not know why  did you registered in Github just one hour ago, and the only thing you have done is asking this question. 

If you targeted  to offend anonymously. OK, you did it. But, I would like to let you know that I am not the owner of the node, and I do not know who is. Actually, I have my node on my computer I guess you do not know, and may not be able to figure it out. 

@merced , I think you may not know this is at least the 5th attacks from different nodes like this related to weight calculation flaw since the 0.5 user-devnet launched on Sep. 25th. I would think there will be more before the fix is in. Just like what you might already saw in 0.2.3 devnet, miners used fake VDF issue to shorten block times. There were many times too. The expectation of the network come to normal without fix is not realistic. I am not surprised this network is attacked again and again, since it is in this stage, the earlier you find issue, the better we could find a solution. 

Once the issue is found, I agree that we try more things to find more issues, instead of to reproduce the  same issue. I would like to suggest all miners to move on to test more - other functions, performance, try more issues, while leaving this before fix is available, since this issue is quite clear and a solution is almost ready.

**Comment by ridewindx** [comment]
The user devnet has been broken for many days. So we would not use it again at present, and should wait for fix by filecoin team.

If you want to test something of yourself, you should launch your local testnet.

**Comment by iMiamasJohano** [comment]
都别在这装清高了   
从上线一开始楼上某位的提前生成攻击  
到后来另外某位的权重攻击
再到后面的又是某位的权重攻击
天下乌鸦一般黑  没必要装白天鹅

**Comment by a8159236** [comment]
I searched through a search engine for a website with the same name: https://forcepool.cn/home/index

**Comment by a8159236** [comment]
I searched through a search engine for a website with the same name: https://forcepool.cn/home/index
Are you talking about forcepool?

**Comment by diwufeiwen** [comment]
Some attacks are for the government to better find problems, some are purely malicious attacks, for their own reputation. @iMiamasJohano

**Comment by iMiamasJohano** [comment]
> Some attacks are for the government to better find problems, some are purely malicious attacks, for their own reputation. @iMiamasJohano

1. I agree to find the problem and fix it as soon as possible.
2. I object to malicious attacks that cause the chain to be unavailable, which has no benefit to Filecoin.
3. Since you attacked it with other vulnerabilities earlier and also advertised yourself with the attack, 就别在这装清高

**Comment by steven004** [comment]
As mentioned earlier, a few more attacks happened in these days, and still ongoing. It is expected, there were more miners trying. 

Agree with @ridewindx , leave it for the team to fix, and you may run more test on your local net, and submit issues once found.

**Comment by huaxiaone** [comment]
刚开始的一次攻击，算是给开发网找漏洞，后面的几次重复攻击是何意啊？
丢人丢到国际上了都。
这标题一上来就扣帽子给原力区，是不是不妥啊。
第一次攻击网络的是谁呢，肯定不是原力区，因为当时原力区是排名第一，没有必要攻击网络。

**Comment by eshon** [comment]
It's been really frustrating for everyone trying to mine. 

Some of you are incorrect about who is a malicious node.

Please be polite and respectful to each other! In our Code of Conduct, we want this to be a **friendly, harassment-free space**:

https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md
