### ISSUE TITLE
Bound Syncer Dispatcher's work queue

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/go-filecoin#3583]
### Description
We expect many syncing targets to propagate to the syncer dispatcher.  We also expect the work done by the syncer to potentially take a very long time to complete.  To prevent the work queue from building up a large number of targets, many of which will be useless by the time the syncer is ready for another target, we should bound the work queue. 

Proposal: In the case the work queue hits the bound we can insert all incoming targets onto the work queue and then use the heap `Remove` method to remove the last `totalTargets - workQueueBound` targets on the queue.  This way we keep the bound and only drop the lowest priority targets.

### Acceptance criteria
Bounded dispatcher worker queue that keeps highest priority targets

### Risks + pitfalls
There is a remote possibility this introduces time dependence into the tests in the case something is going really wrong there.  Probably we are never hitting any >10 bound in tests so its not going to be an issue.

### Where to begin
It makes sense to add this checking and removing to the `TargetQueue` type.  Either we can do it each time within `Push` or we can add a `MaybeTrim` (or something) method.

**Comment by anorth** [comment]
I'm not sure this is safe. If "high priority" means high reported height, then malicious messages with unverified heights could crowd out the real chain.

Safer and simpler would be to just drop inbound on the floor if the queue is full, wait for space to appear. (Dropping older, rather than newer, could be slightly more efficient, but probably not worth the bookkeeping). More sophisticated rate limiting would probably take the source into account too.
