### ISSUE TITLE
Windows install report

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/go-filecoin#935]
This is a holding bin for @djdv’s adventures in windows.

**Comment by djdv** [comment]
Current (94b2894473e57c44d60164f89f417694ea3911db) state of things:
Test environment was a Windows 10 machine, inside `cmd` and `bash` shells.
Go and Rust binaries are first party native Windows variants.
All POSIX tools come from [MSYS2 ](https://www.msys2.org/) package repos (bash, git, curl, et al.).
***
`build/main.go` makes shell assumption (this is reasonable but causes issues when not using a POSIX shell)
`cmd("./scripts/whatever.sh")` needs to prefix the appropriate interpreter somehow.
i.e. `cmd("sh ./scripts/whatever.sh")`.
***
Inside `scripts/install-rust-fil-proofs.sh`. if `FILECOIN_USE_PRECOMPILED_RUST_PROOFS` is set (the "Getting Started" wiki page currently suggests it), the build will fail in an ambiguous way if precompiled variants are not available for the platform.
`RELEASE_URL` will be blank causing `curl` to fail with: `curl: (3) <url> malformed`

My system is looking for `rust-fil-proofs-MSYS_NT-10.0` on the remote, which [currently ](https://api.github.com/repos/filecoin-project/rust-fil-proofs/releases/tags/075c6a3dba29bfb0)does not exist.
***
There seems to be some issue with the `filecoin-proofs` build script. I'm not very familiar with Rust so I wasn't able to go much deeper than this.
My hunch here is that `cargo` itself or the build script it's invoking, is missing compiler/linker flags, or may be invoking an incompatible compiler. I say this because it's failing to handle a C standard library, but I can't see specifically what it's calling when it gets to that point in the build.

```
filecoin-project/go-filecoin/proofs/rust-fil-proofs> cargo --verbose build --release --all

...

Compiling filecoin-proofs v0.1.0 (C:\Users\Dominic Della Valle\Projects\Go\src\github.com\filecoin-project\go-filecoin\proofs\rust-fil-proofs\filecoin-proofs)
     Running `C:\Users\Dominic Della Valle\Projects\Go\src\github.com\filecoin-project\go-filecoin\proofs\rust-fil-proofs\target\release\build\filecoin-proofs-962b10d86e78f6c3\build-script-build`
error: failed to run custom build command for `filecoin-proofs v0.1.0 (C:\Users\Dominic Della Valle\Projects\Go\src\github.com\filecoin-project\go-filecoin\proofs\rust-fil-proofs\filecoin-proofs)`
process didn't exit successfully: `C:\Users\Dominic Della Valle\Projects\Go\src\github.com\filecoin-project\go-filecoin\proofs\rust-fil-proofs\target\release\build\filecoin-proofs-962b10d86e78f6c3\build-script-build` (exit code: 1)
--- stderr
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:360:47: error: expected ';' after top level declarator
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:361:48: error: expected ';' after top level declarator
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:365:26: error: expected ';' after top level declarator
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:656:69: error: expected ';' after top level declarator
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:658:48: error: expected ';' after top level declarator
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:659:55: error: expected ';' after top level declarator
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:360:47: error: expected ';' after top level declarator, err: true
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:361:48: error: expected ';' after top level declarator, err: true
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:365:26: error: expected ';' after top level declarator, err: true
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:656:69: error: expected ';' after top level declarator, err: true
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:658:48: error: expected ';' after top level declarator, err: true
C:\msys64\mingw64\x86_64-w64-mingw32\include\stdlib.h:659:55: error: expected ';' after top level declarator, err: true
unable to generate bindings: ()
```

Because I'm unable to build `paramfetch` etc., I can't continue the build process.

**Comment by anorth** [comment]
For #2258
